export const enums = {
  name: {
  DESCRIPTION: 'description',
  CIRCUMFERENCE: 'circumference',
  EXPOSURE: 'exposure',
  CAP_SHAPE: 'cap shape',
  CAP_COLOUR: 'cap colour',
  CAP_DIAMETER: 'cap diameter',
  CAP_WIDTH: 'cap width',
  CAP_HEIGHT: 'cap height',
  SHELF_WIDTH: 'shelf width',
  SHELF_THICKNESS: 'shelf tHickness',
  ECO_TYPE: 'ecological type',
  HOW_EDIBLE: 'how edible',
  HYMENIUM_TYPE: 'hymenium type',
  SPORE_PRINT_COLOUR: 'spore print colour',
  STIPE_CHARACTER: 'stipe character',
  STIPE_LENGTH: 'stipe length',
  STIPE_WIDTH: 'stipe width',
  STIPE_COLOUR: 'stipe colour',
  GILL_ATTACHMENT: 'gill attachment',
  FLESH: 'flesh',
  STEM_CHARACTER: 'stem character',
  GILL_COLOUR: 'gill colour',
  TRUNK_COLOUR: 'trunk colour',
  SUBSTRATE: 'substrate',
  THALLUS_TYPE: 'thallus type',
  RHIZINE_TYPE: 'rhizine type',
  DISC_WIDTH: 'Width',
  LOBE_WIDTH: 'Lobe width',
  LOBE_LENGTH: 'Lobe length',
  LOBE_DIAMETER: 'Lobe diameter',
  ROLE: 'Role',
  NATIVE: 'Native',
  NATIVE_TO: 'Native to',
  SYMBIOSIS: 'Symbiosis',
  ASSOCIATE: 'associate',
  SYMBIONTS: 'symbionts',
  LOOKALIKES: 'look alikes',
  ECOLOGY: 'ecology',
  HABITAT: 'habitat',
  TROPHIC_LEVEL: 'Trophic level',
  ORGANISATION: 'Organisation',
  SMELL: 'smell',
  FRUIT_TYPE: 'Fruit type',
  FRUIT_WIDTH: 'Fruit width',
  FRUIT_HEIGHT: 'Fruit height',
  FRUIT_DIAMETER: 'Fruit diameter',
  FRUIT_LENGTH: 'Fruit length',
  FRUIT_COLOUR: 'Fruit colour',
  FRUIT_TEXTURE: 'Fruit texture',
  BRANCH_TEXTURE: 'Branch texture',
  FRUIT_SURFACE: 'Fruit surface',
  SEED_DISPERSAL: 'Seed dispersal',
  VITAMINS: 'vitamins',
  STAMEN_COUNT: 'Stamen count',
  STYLE_COUNT: 'Style count',
  LEAFLET_COUNT: 'Leaflet count',
  LOBE_COUNT: 'Lobe count',
  LEAFLET_LENGTH: 'Leaflet length',
  LEAFLET_WIDTH: 'Leaflet width',
  GROUPING: 'grouping',
  MEDICINAL_PROPERTIES: 'Medicinal properties',
  COLOUR: 'Colour',
  USAGE: 'Usage',
  FORM: 'Form',
  LIFE_SPAN: 'Life span',
  GERMINATION: 'Germination',
  ACTIVE: 'Active',
  SUBSTRATE_ADHERANCE: 'Substrate adherance',
  RANK: 'UK Rank',
  SIZE: 'Size',
  LENGTH: 'Length',
  VOICE: 'Voice',
  HEIGHT: 'Height',
  WEIGHT: 'Weight',
  REPRODUCTION: 'Reproduction',
  ASEXUAL_REPRODUCTION: 'Asexual reproduction',
  DISPLAY: 'Display',
  BEHAVIOUR: 'behaviour',
  CHARACTERISTIC: 'Characteristic',
  COMMUNICATION: 'Communication',
  SHELTER: 'Shelter',
  DISEASE: 'Disease',
  THREAT: 'Threat',
  FOOD: 'Food',
  SEXUAL_DIMORPHISM: 'Sexual dimorphism',
  WING_SPAN: 'Wing span',
  TREE_SHAPE: 'Tree shape',
  CROWN_SHAPE: 'Crown shape',
  LEAF_DIVISION: 'Leaf division',
  LEAFLET_DIVISION: 'Leaflet division',
  LEAF_BLADE: 'Leaf blade',
  LEAF_VARIATION: 'Leaf variation',
  LEAF_SHAPE: 'Leaf shape',
  JUVENILE_LEAF_SHAPE: 'Juvenile leaf shape',
  LEAF_MARGIN: 'Leaf margin',
  LEAF_ARRANGEMENT: 'Leaf arrangement',
  LEAF_ATTACHMENT: 'Leaf attachment',
  LEAF_LENGTH: 'Leaf length',
  JUVENILE_LEAF_LENGTH: 'Juvenile leaf length',
  LEAF_WIDTH: 'Leaf width',
  LEAF_COLOUR: 'Leaf colour',
  LEAF_SURFACE: 'Leaf surface',
  LEAF_ABOVE_SURFACE: 'Leaf above surface',
  LEAF_BELOW_SURFACE: 'Leaf below surface',
  LEAF_TEXTURE: 'Leaf texture',
  JUVENILE_TEXTURE: 'Juvenile leaf texture',
  LEAF_SHAPE: 'Leaf shape',
  LEAFLET_SHAPE: 'Leaflet shape',
  LEAF_BELOW_COLOUR: 'Leaf below colour',
  LEAF_ABOVE_COLOUR: 'Leaf above colour',
  LEAF_VENATION: 'Leaf venation',
  LEAF_BUNDLE_COUNT: 'Leaf bundle count',
  LEAF_FEATURES: 'Leaf features',
  LEAF_FOLDING: 'Leaf folding',
  BRANCH_ARRANGEMENT: 'Branch arrangement',
  STALK_HEIGHT: 'Stalk height',
  STEM_HEIGHT: 'Stem height',
  STEM_DIAMETER: 'Stem diameter',
  TRUNK_DIAMETER: 'Trunk diameter',
  BRACT_COLOUR: 'Bract colour',
  BRACT_LENGTH: 'Bract length',
  PETIOLE_LENGTH: 'Petiole length',
  FLOWER_DIAMETER: 'Flower diameter',
  FLOWER_LENGTH: 'Flower length',
  FLOWER_COLOUR: 'Flower colour',
  FLOWER_SHAPE: 'Flower shape',
  PETAL_COUNT: 'Petal count',
  LEAFLET_COUNT: 'Leaflet count',
  PETAL_LENGTH: 'Petal length',
  PETAL_WIDTH: 'Petal width',
  PETAL_COLOUR: 'Petal colour',
  SEPAL_COUNT: 'Sepal count',
  INFLORESCENCE: 'Inflorescence',
  FEMALE_CONE_LENGTH: 'Female cone length',
  MALE_CONE_LENGTH: 'Male cone length',
  CONE_LENGTH: 'Cone length',
  FEMALE_CONE_WIDTH: 'Female cone width',
  MALE_CONE_WIDTH: 'Male cone width',
  CONE_WIDTH: 'Cone width',
  CONE_DIAMETER: 'Cone diameter',
  CONE_COLOUR: 'Cone colour',
  CONE_SHAPE: 'Cone shape',
  MALE_CONE_COLOUR: 'Male cone colour',
  FEMALE_CONE_COLOUR: 'Female cone colour',
  CONE_SCALE_COUNT: 'Cone scale count',
  BARK_TYPE: 'Bark type',
  BARK_TEXTURE: 'Bark texture',
  CAP_TEXTURE: 'Cap texture',
  BARK_COLOUR: 'Bark colour',
  ALLOCHORY: 'Allochory',
  REPRODUCTIVE_CONTAINER: 'Reproductive container',
  CATERPILLAR_FOOD: 'Caterpillar food',
  CATERPILLAR_LENGTH: 'Caterpillar length',
  CATERPILLAR_COLOUR: 'Caterpillar colour',
  HIBERNATING_STAGE: 'Hibernating stage',
  PHYSIOLOGY: 'Physiology',
  MATING: 'Mating season',
  MATING_SYSTEM: 'mating system',
  PREGNANCY: 'Pregnancy',
  LITTER_SIZE: 'Litter size',
  JUVENILE: 'Juvenile',
  GESTATION: 'Gestation',
  WEANING: 'Weaning',
  LACTATION: 'Lactation',
  SENSORY_ACUITY: 'Sensory acuity',
  CRYPSIS: 'Crypsis',
  CACHE_SIZE: 'Number of caches',
  COLLECTIVE: 'Collective',
  FEMALE: 'Female',
  MALE: 'Male',
  TAIL_LENGTH: 'Tail length',
  MAX_SPEED: 'Maximum speed',
  DIET: 'Diet',
  ALTRICIAL: 'Altricial',
  MOULTING: 'Moulting',
  MATURITY: 'Maturity',
  FUNGUS_MARGIN_TYPE: 'Fungus margin type',
  SOIL_TYPE: 'Soil type',
  PH: 'pH',
  PH_VALUE: 'pH value',
  LICEN_CUP_COLOUR: 'Licen cup colour',
  RIM: 'Rim',
  CENTRE: 'Centre',
  POLLINATION: 'Pollination',
  PROPAGATION: 'Propagation',
  CLIMATE: 'Climate',
  SONG: 'Song',
  DIAMETER: 'diameter',
  NUT_TYPE: 'nut type',
  TREE_ECOLOGY: 'Tree ecology',
  KEY_FEATURE: 'Key feature', 
  GILL_ATTACHMENT : 'gill attachment',
  MUSHROOM_GROUP : 'Mushroom group',
  QUEEN_LENGTH: 'Queen length',
  QUEEN_WINGSPAN: 'Queen wingspan',
  QUEEN_WEIGHT: 'Queen weight',
  WORKER_LENGTH: 'Worker length',
  WORKER_WINGSPAN: 'Worker wingspan',
  WORKER_WEIGHT: 'Worker weight',
  MALE_LENGTH: 'Male length',
  MALE_WINGSPAN: 'Male wingspan',
  MALE_WEIGHT: 'Male weight',
  COLONY_SIZE: 'colony size',
  TONGUE_LENGTH: 'Tongue length',
  INFRUCTESCENCE_LENGTH: 'Infructescence length',
  INFRUCTESCENCE_WIDTH: 'Infructescence width',
  UMBEL_DIAMETER: 'Umbel diameter',
  WIDTH: 'Width',
  BREADTH: 'Breadth',
  UMBEL_TYPE: 'Umbel type',
  },
  howEdible: {
  help: 'How edible is this species?',
  CHOICE: 'Choice',
  EDIBLE: 'Edible',
  INEDIBLE: 'Inedible',
  POISONOUS: 'Poisonous',
  DEADLY: 'Deadly',
  TOXIC: 'Toxic',
  type: 'howEdible',
  name: 'how edible'
  },
  habitat: {
  help: 'What is the habitat of this species?',
  WOOD: 'Wood',
  WOODLAND: 'Woodland',
  WOODLAND_LITTER: 'Woodland litter',
  GRASSLAND: 'Grassland',
  SOIL: 'Soil',
  VEGETATION: 'Vegetation',
  DUNG: 'Dung',
  DUNES: 'Dunes',
  WIDESPREAD: 'Widespread',
  DEAD_WOOD: 'Dead wood',
  WASTELAND: 'Wasteland',
  MEADOW: 'Meadow',
  FIELDS: 'Fields',
  MOSS: 'Moss',
  PASTURE: 'Pasture',
  BARK: 'Bark',
  SHOOTS: 'Shoots',
  COMMONS: 'Common',
  HEATH: 'Heath',
  ORCHARDS: 'Orchards',
  HEDGEROWS: 'Hedgerows',
  LAWNS: 'Lawns',
  RINGS: 'Rings',
  DAMP: 'Damp',
  TREE_BASE: 'Tree base',
  FOREST_EDGE: 'Forest edge',
  PARKS: 'Parks',
  TRUNKS: 'Trunks',
  STUMPS: 'Stumps',
  ROCKS: 'Rocks',
  FENCES: 'Fences',
  TREES: 'Trees',
  SHRUBS: 'Shrubs',
  SHRUBLAND: 'Shrubland',
  MARSHLAND: 'Marshland',
  EXPOSED_WOOD: 'Exposed wood',
  BRANCHES: 'Branches',
  HILLS: 'Hills',
  URBAN: 'Urban',
  VALLEYS: 'Valleys',
  MAQUIS: 'Maquis',
  SAVANNA: 'Savanna',
  FOREST_STEPPE: 'Forest steppe',
  MEADOW_STEPPE: 'meadow steppe',
  BOREAL: 'Boreal',
  SCRUB: 'Scrub',
  WALLS: 'Walls',
  MOORLAND: 'Moorland',
  COAST: 'Coast',
  BRUSH: 'Brush',
  WATER: 'Water',
  SNOW: 'Snow',
  NO_SNOW: 'No snow',
  CONIFERS: 'conifers',
  BROAD_LEAF: 'broad-leaf',
  PINE: 'pine',
  BEECH: 'beech',
  OAK: 'oak',
  DITCH: 'Ditch',
  WET_MEADOW: 'Wet meadow',
  LAKESIDE: 'Lakeside',
  RIPERIAN: 'Riperian',
  WETLANDS: 'Wetlands'
  },
  ecologicalType: {
  help: 'What is the ecological type of this mushroom?',
  SAPROTROPHIC: 'Saprotrophic',
  PARASITIC: 'Parasitic',
  MYCORRHIZAL: 'Mycorrhizal',
  PLANT_PATHOGEN: 'Plant pathogen',  
  },
  capShape: {
  help: 'How would you describe the pileus?',
  
  CAMPANULATE: 'Campanulate',
  CONICAL: 'Conical',
  CONVEX: 'Convex',
  DEPRESSED: 'Depressed',
  FLAT: 'Flat',
  INFUNDIBULIFORM: 'Infundibuliform',
  OFFSET: 'Offset',
  OVATE: 'Ovate',
  UMBILLICATE: 'Umbillicate',
  UMBONATE: 'Umbonate',
  
  POTATO_SHAPED: 'Potato shaped',
  NA: 'N/A',
  SPHERICAL: 'Spherical',
  PEAR_SHAPED: 'Pear shaped',
  BRAIN_LIKE: 'Brain-like',
  HONEYCOMB: 'Honeycomb',
  HEMI_SPHERICAL: 'Hemispherical',
  type: 'capShape',
  name: 'cap shape'
  },
  treeEcology: {
  OAK: 'Oak',
  BEECH: 'Beech',
  BIRCH: 'Birch',
  DECIDUOUS: 'Deciduous',
  SOFTWOOD: 'Softwood',
  HARDWOOD: 'Hardwood',
  MIXED_WOODLAND: 'Mixed woodland',
  CONIFEROUS: 'Coniferous',
  PINE: 'Pine',
  ELM: 'Elm',
  ASH: 'Ash',
  SYCAMORE: 'Sycamore',
  ASPEN: 'Aspen',
  ELDER: 'Elder',
  CHESTNUT: 'Chestnut',
  HARDWOODS: 'Hardwoods',
  PRUNUS: 'Prunus',
  PYRUS: 'Pyrus',
  SALIX: 'Salix',
  ROBINIA: 'Robinia',
  CERATONIA: 'Ceratonia',
  EUCALYPTUS: 'Eucalyptus',
  BROAD_LEAF: 'Broad-leaf',
  SWEET_CHESTNUT: 'Sweet chestnut',
  POPLAR: 'Poplar',
  CORK: 'Cork',
  FIR: 'Fir',
  SPRUCE: 'Spruce',
  PLANE: 'Plane',
  WILLOW: 'Willow',
  MAPLE: 'Maple',
  LARCH: 'Larch',
  CEDAR: 'Cedar',
  YEW: 'Yew',
  TURKEY_OAK: 'Turkey oak',
  HAWTHORN: 'Hawthorn',
  BUSH: 'Bush',
  SHRUB: 'Shrub',
  },
  hymeniumType: {
  help: 'What is the hymenium type?',
  GILLS: 'Gills',
  PORES: 'Pores',
  GLEBA: 'Gleba',
  SMOOTH: 'Smooth',
  TEETH: 'Teeth',
  RIDGES: 'Ridges',
  FALSE_GILLS: 'False gills',
  },
  associate: {
  ALGA: 'Alga',
  CYNOBACTERIUM: 'Cyanobacterium',
  FUNGUS: 'Fungus',
  type: 'associate',
  name: 'associate'
  },
  thallusType: {
  help: 'What is this lichen\'s thallus type?',
  FOLIOSE: 'Foliose',
  FRUTICOSE: 'Fruticose',
  CRUSTOSE: 'Crustose',
  SQUAMULOSE: 'Squamulose',
  LEPROSE: 'Leprose',
  EPIPHYTE: 'Epiphyte',
  type: 'thallusType',
  name: 'thallus type'
  },
  rhizineType: {
  SPARSE: 'Sparse',
  HAPTER: 'Hapter',
  type: 'rhizineType',
  name: 'rhizine type'
  },
  substrate: {
  WOOD: 'Wood',
  BARK: 'Bark',
  ROCKS: 'Rocks',
  SOIL: 'Soil',
  type: 'substrate',
  name: 'substrate'
  },
  level: {
  HIGH: 'High',
  MEDIUM: 'Medium',
  LOW: 'Low',
  VARIABLE: 'Variable',
  type: 'level',
  name: 'level'
  },
  medicinalProperties: {
  ANTIVIRAL: 'Antiviral',
  ANTISEPTIC: 'Antiseptic',
  ANTI_INFLAMMATORY: 'Anti-inflammatory',
  ANTIBIOTIC: 'Antibiotic',
  ANLAGESIC: 'Analgesic',
  ANTIBACTERIAL: 'Antibacterial',
  ANTICOAGULANT: 'Anticoagulant',
  ANTIFUNGAL: 'Antifungal',
  type: 'medicinalProperties',
  name: 'medicinal properties'
  },
  ph: {
  ACIDIC: 'Acidic',
  ALKALINE: 'Alkaline',
  NEUTRAL: 'Neutral',
  type: 'pHLevel',
  name: 'ph level'
  },
  colour: {
  // help: 'Which colour best describes this species?',
  LILAC: 'Lilac',
  BUFF: 'Buff',
  WHITE: 'White',
  YELLOW: 'Yellow',
  DARK_GREEN: 'Dark green',
  GREEN: 'Green',
  WHITE_GREEN: 'White-green',
  BRIGHT_GREEN: 'Bright green',
  OLIVE_GREEN: 'Olive-green',
  BRIGHT_YELLOW_GREEN: 'Bright yellow-green',
  YELLOW_GREEN: 'Yellow-green',
  YELLOW_BROWN: 'Yellow-brown',
  PURPLE_BROWN: 'Purple-brown',
  GREY_BROWN: 'Grey-brown',
  DARK_YELLOW: 'Dark yellow',
  DARK_RED: 'Dark red',
  DARK_PINK: 'Dark pink',
  ORANGE: 'Orange',
  BLOOD_RANGE: 'Blood orange',
  RED: 'Red',
  RED_BROWN: 'Red-brown',
  ORANGE_RED: 'Orange-red',
  GREY: 'Grey',
  PALE_GREY: 'Pale grey',
  PALE_BROWN: 'Pale brown',
  GREY_GREEN: 'Grey-green',
  GREY_WHITE: 'Grey-white',
  BROWN: 'Brown',
  CHESTNUT_BROWN: 'Chestnut brown',
  PAPER_BROWN: 'Paper brown',
  BLACK: 'Black',
  BLUE: 'Blue',
  PALE_BLUE: 'Pale blue',
  BLUE_BLACK: 'Blue-black',
  JET_BLACK: 'Jet-black',
  BLUE_GREEN: 'Blue-green',
  VIOLET: 'Violet',
  BURGUNDY: 'Burgundy',
  PALE_VIOLET: 'Pale violet',
  VIOLET_PURPLE: 'Violet purple',
  PALE_GREEN: 'Pale green',
  PALE_YELLOW: 'Pale yellow',
  PALE_YELLOW_GREEN: 'Pale yellow-green',
  PALE_GREY_GREEN: 'Pale yellow-green',
  GLAUCOUS: 'Glaucous',
  GREY_YELLOW: 'Grey-yellow',
  ORANGE_YELLOW: 'Orange-yellow',
  CREAM: 'Cream',
  CHALKY: 'Chalky',
  PINK: 'Pink',
  PALE_PINK: 'Pale pink',
  PURPLE: 'Purple',
  PALE_PURPLE: 'Pale purple',
  DARK_PURPLE: 'Dark purple',
  TAN: 'Tan',
  DARK_BROWN: 'Dark brown',
  HONEY: 'Honey',
  RED_PURPLE: 'Red-purple',
  type: 'colour',
  name: 'colour'
  },
  usage: {
  help: 'To what use do humans put this species?',
  PERFUMERY: 'Perfumery',
  TANNING: 'Tanning',
  DYING: 'Dying',
  BREWING: 'Brewing',
  FOOD: 'Food',
  WINE: 'Wine',
  COFFEE: 'Coffee',
  TEA: 'Tea',
  BIRDS_NEST: 'Bird\'s nest',
  POISON: 'Poison',
  FODDER: 'Fodder',
  GREEN_MANURE: 'Green manure',
  MEDICINE: 'Medicine',
  FUR: 'Fur',
  TIMBER: 'Timber',
  PEST_CONTROL: 'Pest control',
  HERB: 'Herb',
  SPICE: 'Spice',
  ESSENTIAL_OIL: 'Essential oil',
  MORDANT: 'Mordant',
  ASTRINGENT: 'Astringent'
  },
  nonTaxaType: {
  FORM: 'Form',
  type: 'nonTaxaType',
  name: 'non taxa type'
  },
  element: {
  NITROGEN: 'Nitrogen',
  SULPUR_DIOXIDE: 'Sulpur dioxide',
  type: 'element',
  name: 'element'
  },
  leafBlade: {
  SIMPLE: 'Simple ',
  COMPOUND: 'Compound',
  type: 'leaf blade',
  name: 'leaf blade'
  },
  leafDivision: {
  PALMATE: 'Palmate',
  COMPOUND_PALMATE: 'Compound Palmate',
  PALMATELY_LOBED: 'Palmately lobed',
  PINNATE: 'Pinnate',
  COMPOUND_PINNATE: 'Compound Pinnate',
  ODD_PINNATE: 'Odd pinnate',
  EVEN_PINNATE: 'Even pinnate',
  BIPINNATE: 'Bipinnate',
  COMPOUND_BIPINNATE: 'Compound Bipinnate',
  TRIFOLIATE: 'Trifoliate',
  PINNATIFID: 'Pinnatifid',
  TRIPINNATE: 'Tripinnate',
  SIMPLE: 'Simple ',
  COMPOUND: 'Compound',
  IMPARIPINNATE: 'Imparipinnate',
  PARIPINNATE: 'Paripinnate',
  },
  leafletDivision: {
  PALMATE: 'Palmate',
  COMPOUND_PALMATE: 'Compound Palmate',
  PALMATELY_LOBED: 'Palmately lobed',
  PINNATE: 'Pinnate',
  COMPOUND_PINNATE: 'Compound Pinnate',
  ODD_PINNATE: 'Odd pinnate',
  EVEN_PINNATE: 'Even pinnate',
  BIPINNATE: 'Bipinnate',
  COMPOUND_BIPINNATE: 'Compound Bipinnate',
  TRIFOLIATE: 'Trifoliate',
  PINNATIFID: 'Pinnatifid',
  TRIPINNATE: 'Tripinnate',
  SIMPLE: 'Simple ',
  COMPOUND: 'Compound',
  },
  leafVariation: {
  HOMOBLASTIC: 'Homoblastic',
  HETEROBLASTIC: 'Heteroblastic',
  type: 'leafVariation',
  name: 'leaf variation'
  },
  shape: {
  LINEAR: 'Linear',
  OVATE: 'Ovate',
  OBLANCEOLATE: 'Oblanceolate',
  OBOVATE: 'Obovate',

  ACICULAR: 'Acicular',
  ACUMINATE: 'acuminate',
  ACUTE: 'acute',
  APICULATE: 'apiculate',
  ATTENUATE: 'attenuate',
  AURICULATE: 'auriculate',
  ASYMMETRICAL: 'asymmetrical',
  CAUDATE: 'caudate',
  CORDATE: 'cordate',
  CUNEATE: 'cuneate',
  CUSPIDATE: 'cuspidate',
  DELTOID: 'deltoid',
  DIGITATE: 'digitate',
  ELLIPTIC: 'elliptic',
  ENSIFORM: 'ensiform',
  EMARGINATE: 'emarginate',
  FALCATE: 'falcate',
  FENESTRATE: 'fenestrate',
  FILIFORM: 'filiform',
  FLABELLATE: 'flabellate',
  HASTATE: 'hastate',
  LACINIATE: 'laciniate',
  LANCEOLATE: 'lanceolate',
  LAMINAR: 'laminar',
  LINEAR: 'linear',
  LOBED: 'lobed',
  LORATE: 'lorate',
  LYRATE: 'lyrate',
  MUCRONATE: 'mucronate',
  MULTIFID: 'multifid',
  OBCORDATE: 'obcordate',
  OBLANCEOLATE: 'oblanceolate',
  OBLIQUE: 'oblique',
  OBLONG: 'oblong',
  OBOVATE: 'obovate',
  OBTRULLATE: 'obtrullate',
  OBTUSE: 'obtuse',
  ORBICULAR: 'orbicular',
  OVATE: 'ovate',
  PALMATE: 'palmate',
  PALMATELY_LOBED: 'palmately lobed',
  PALMATIFID: 'palmatifid',
  PALMATIPARTITE: 'palmatipartite',
  PALMATISECT: 'palmatisect',
  PANDURATE: 'pandurate',
  PEDATE: 'pedate',
  PELTATE: 'peltate',
  PERFOLIATE: 'perfoliate',
  PERFORATE: 'perforate',
  PINNATELY_LOBED: 'pinnately lobed',
  PINNATIFID: 'pinnatifid',
  PINNATIPARTITE: 'pinnatipartite',
  PINNATISECT: 'pinnatisect',
  PLICATE: 'plicate',
  RENIFORM: 'reniform',
  RETUSE: 'retuse',
  RHOMBOID: 'rhomboid',
  ROUNDED: 'rounded',
  TRIANGULAR: 'Triangular',
  QUADRANGULAR: 'Quadrangular',
  SEMITERETE: 'semiterete',
  SINUATE: 'sinuate',
  SAGITTATE: 'sagittate',
  SPATULATE: 'spatulate',
  SPEAR_SHAPED: 'spear-shaped',
  SUBOBTUSE: 'subobtuse',
  SUBULATE: 'subulate',
  TERETE: 'terete',
  TRULLATE: 'trullate',
  TRUNCATE: 'truncate',
  UNDULATE: 'undulate',
  UNIFOLIATE: 'unifoliate',
  FLAT: 'Flat',
  NEEDLE: 'Needle',
  },
  reproduction: {
  SELF_POLLINATION: 'Self-pollination',
  CROSS_POLLINATION: 'Cross-pollination',
  type: 'reproduction',
  name: 'reproduction'
  },
  asexualReproduction: {
  BUDDING: 'budding',
  FRAGMENTATION: 'fragmentation',
  FISSION: 'fission',
  SPORE_FORMATION: 'spore formation',
  VEGETATIVE_PROPAGATION: 'vegetative propagation',
  type: 'asexualReproduction',
  name: 'asexual reproduction'
  },
  leafArrangement: {
  ALTERNATE: 'Alternate',
  BASAL: 'Basal',
  CAULINE: 'Rosulate',
  OPPOSITE: 'Opposite',
  WHORLED: 'Whorled',
  ROWS: 'Rows',
  SPIRAL: 'Spiral',
  OVERLAPPING: 'Overlapping',
  INCURVED: 'Incurved',
  DECUSSATE: 'Decussate',
  type: 'leafArrangement',
  name: 'leaf arrangement'
  },
  leafAttachment: {
    SESSILE: 'Sessile',
    SUBSESSILE: 'Subsessile',
    PEDICELLATE: 'Pedicellate',
  },
  leafMargin: {
  ENTIRE: 'Entire',
  CILIATE: 'Ciliate',
  CRENATE: 'Crenate',
  DENTATE: 'Dentate',
  DENTICULATE: 'Denticulate',
  DOUBLY_SERRATE: 'Doubly serrate',
  SERRATE: 'Serrate',  
  SERRULATE: 'Serrulate',  
  SINUATE: 'Sinuate',  
  LOBATE: 'Lobate',  
  UNDULATE: 'Undulate',  
  SPINY: 'Spiny',  
  SMOOTH: 'Smooth',
  type: 'leafMargin',
  name: 'leaf margin'
  },
  food: {
  GRASS: 'Grass',
  ROTTEN_FRUIT: 'Rotten fruit',
  NECTAR: 'Nectar',
  HONEYDEW: 'Honeydew',
  SEEDS: 'Seeds',
  NUTS: 'Nuts',
  GRAINS: 'Grains',
  BERRIES: 'Berries',
  HERBAGE: 'Herbage',
  SWARD: 'Sward',
  LEAVES: 'Leaves',
  WOOD: 'Wood',
  ROOTS: 'Roots',
  TUBERS: 'Tubers',
  RHIZOMES: 'Rhizomes',
  BULBS: 'Bulbs',
  BARK: 'Bark',
  SHOOTS: 'Shoots',
  type: 'food',
  name: 'food'
  },
  hibernatingStage: {
  ADULT: 'Adult',
  CATERPILLAR: 'Caterpillar',
  PUPA: 'Pupa',
  type: 'hibernatingStage',
  name: 'hibernating stage'
  },
  symbiosis: {
  MUTUALISM: 'Mutualism',
  COMMENSALISM: 'Commensalism',
  PREDATION: 'Predation',
  PARASITISM: 'Parasitism',
  HERBIVORY: 'Herbivory',
  COMPETITION: 'Competition',
  MYCORRHIZAL: 'Mycorrhizal',
  ECTOMYCORRHIZAL: 'Ectomycorrhizal',
  COMPANION: 'Companion planting',
  POLLINATION: 'Pollination',
  SEED_PREDATION: 'Seed predation',
  type: 'symbiosis',
  name: 'symbiosis'
  },
  trophicLevel: {
  help: 'What is the trophic level or this species?',
  PRIMARY_PRODUCER: 'Primary producer',
  PRIMARY_CONSUMER: 'Primary consumer',
  SECONDARY_CONSUMER: 'Secondary consumer',
  OMNIVORE: 'Omnivore',
  TERTIARY_CONSUMER: 'Tertiary consumer',
  APEX_PREDATOR: 'Apex predator',
  type: 'trophicLevel',
  name: 'trophic level'
  },
  shelter: {
  help: 'What is the name of this species`s shelter?',
  DREY: 'Drey',
  BURROW: 'Burrow',
  DEN: 'Den',
  WARREN: 'Warren',
  SETT: 'Sett',
  ROOKERY: 'Rookery',
  LODGE: 'Lodge',
  DAM: 'Dam',
  NEST: 'Nest',
  SHELTER: 'Shelter',
  VEGETATION: 'vegetation',
  type: 'shelter',
  name: 'shelter'
  },
  active: {
  help: 'When is this species most active?',
  CREPUSCULAR: 'Crepuscular',
  DIURNAL: 'Diurnal',
  NOCTURNAL: 'Nocturnal',
  MATUTINAL: 'Matutinal',
  VESPERTINE: 'Vespertine',
  type: 'active',
  name: 'active'
  },
  juvenile: {
  help: 'What is the name for the juvenile of this species?',
  KIT: 'Kit',
  SQUEAKER: 'Squeaker',
  CUB: 'Cub',
  KITTEN: 'Kitten',
  CHICK: 'Chick',
  PUP: 'Pup',
  CALF: 'Calf',
  DUCKLING: 'Duckling',
  EYAS: 'Eyas',
  MAGGOT: 'Maggot',
  KID: 'Kid',
  GOSLING: 'Gosling',
  LEVERET: 'Leveret',
  NYMPH: 'Nymph',
  CATERPILLAR: 'Caterpillar',
  LARVA: 'Larva',
  SALAMANQUESA: 'Salamanquesa',
  type: 'juvenile',
  name: 'juvenile'
  },
  month: {
  JANUARY: 'January',
  FEBRUARY: 'February',
  MARCH: 'March',
  APRIL: 'April',
  MAY: 'May',
  JUNE: 'June',
  JULY: 'July',
  AUGUST: 'August',
  SEPTEMBER: 'September',
  OCTOBER: 'October',
  NOVEMBER: 'November',
  DECEMBER: 'December',
  type: 'month',
  name: 'month'
  },
  female: {
  help: 'What is the name for a female of this species?',
  VIXEN: 'Vixen',
  DOE: 'Doe',
  JILL: 'Jill',
  BITCH: 'Bitch',
  SOW: 'Sow',
  HEN: 'Hen',
  DUCK: 'Duck',
  GOOSE: 'Goose',
  PEN: 'Pen',
  type: 'female',
  name: 'female'
  },
  male: {
  help: 'What is the name for a male of this species?',
  BUCK: 'Buck',
  DOG: 'Dog',
  BOAR: 'Boar',
  TOM: 'Tom',
  JACK: 'Jack',
  COCK: 'Cock',
  DRAKE: 'Drake',
  REYNARD: 'Reynard',
  TOD: 'Tod',
  TERCEL: 'Tercel',
  GANDER: 'Gander',
  COB: 'Cob',
  type: 'male',
  name: 'male'
  },
  diet: {
  help: 'How is the diet of this species best described?',
  HERBIVORE: 'Herbivore',
  OMNIVORE: 'Omnivore',
  CARNIVORE: 'Carnivore',
  XYLOPHAGOUS: 'Xylophagous',
  POLYPHAGOUS: 'Polyphagous',
  type: 'diet',
  name: 'diet'
  },
  fungusMarginType: {
  ENTIRE: 'Smooth entire',
  APPENDICULATE: 'Appendiculate',
  UNDULATE: 'Undulate',
  STRIATE: 'Striate',
  PLICATE: 'Plicate',
  RIMMOSE: 'Rimmose',
  ERODED: 'Eroded',
  INROLLED: 'Inrolled',
  type: 'marginType',  
  name: 'fungus margin type'
  },
  soilType: {
  SILICEOUS: 'Siliceous',
  CALCAREOUS: 'Calcareous',
  NITROGENOUS: 'Nitrogenous',
  NUTRIENT_POOR: 'Nutrient poor',
  WELL_DRAINED: 'Well-drained',
  WELL_WATERED: 'Well-watered',
  LOAM: 'Loam',
  CHALK: 'Chalk',
  SAND: 'Sand',
  RICH: 'Rich',
  MOIST: 'Moist'
  },
  organisation: {
  help: 'How is this species organised?',
  EUSOCIAL: 'Eusocial',
  SOCIAL: 'Social',
  SOLITARY: 'Solitary',
  MATRIARCHY: 'Matriarchy',
  type: 'organisation',
  name: 'organisation'
  },
  role: {
  INDICATOR: 'Indicator',
  KEYSTONE: 'Keystone',
  FOUNDATION: 'Foundation',
  SPECIALIST: 'Specialist',
  GENERALIST: 'Generalist',
  PIONEER: 'Pioneer',
  INVASIVE: 'Invasive',
  DOMINANT: 'Dominant',
  POLLINATOR: 'Pollinator',
  PREDATOR: 'Predator',
  HERBIVORE: 'Herbivore',
  OMNIVORE: 'Omnivore',
  CARNIVORE: 'Carnivore',
  GRANIVORE: 'Granivore',
  MUCIVORE: 'Mucivore',
  PREY: 'Prey',
  COMPETITOR: 'Competitor',
  HOST: 'Host',
  CARRIER: 'Carrier',
  RUDERAL: 'Ruderal',
  SUPERTRAMP: 'Supertramp',
  SYMBIONT: 'Symbiont',
  OCCUPANT: 'Lives in',
  PARASITE: 'Parasite',
  COLONISER: 'Coloniser',
  EARLY_SUCCESSION: 'early-succession',
  SEED_DISPERSAL: 'Seed dispersal',
  FERTILISATION: 'Fertilisation',
  PROPAGATION: 'propagation',
  REPRODUCTION: 'reproduction',
  BIOINDICATOR: 'Bioindicator',
  STRANGLER: 'Strangler',
  FOOD_SOURCE: 'Food source',
  EPIPHYTIC: 'Epiphytic',
  EPIPHYTIC_STRANGLER: 'Epiphytic strangler',
  NUTRIENT_CYCLING: 'Nutrient cycling',
  CARBON_DIOXIDE_PRODUCTION:'Carbon dioxide production',
  MYCOREMEDIATION: 'Mycoremediation',
  type: 'role',
  name: 'role'
  },
  fruitType: {
  help: 'What fruit type does this plant have?',
  DRUPE: 'Drupe',
  POME: 'Pome',
  BERRY: 'Berry',
  AGGREGATE_FRUIT: 'Aggregate fruit',
  LEGUME: 'Legume',
  CAPSULE: 'Capsule',
  NUT: 'Nut',
  GRAIN: 'Grain',
  MULTIPLE_FRUIT: 'Multiple fruit',
  SAMARA: 'Samara',
  ACHENE: 'Achene',
  POD: 'Pod',
  ARIL: 'Aril',
  SYCONIUM: 'syconium',
  FOLLICLE: 'Follicle',
  type: 'fruitType',
  name: 'fruit type'
  },
  inflorescence: {
  help: 'What type of inflorescence does this plant have?',
  CATKIN: 'catkin',
  UMBEL: 'umbel',
  RACEME: 'raceme',
  CORYMB: 'corymb',
  SPIKE: 'Spike',
  SPADEX: 'Spadex',
  SINGLE: 'Single',
  PANICLE: 'Panicle',
  CYMOSE: 'Cymose',
  BRANCHED_SPIKE: 'Branched spike',
  },
  umbelType: {
    FLAT: 'Flat',
    SPHERICAL: 'Spherical',
    SIMPLE: 'Simple',
    COMPOUND: 'Compound',
    TERMINAL: 'Terminal',
  },
  display: {
  help: 'Which form of display does this species exhibit?',
  DIEMATIC: 'Diematic',
  SEXUAL_COLOUR_DIMORPHISM: 'Sexual colour dimorphism',
  NO_SEXUAL_COLOUR_DIMORPHISM: 'No sexual colour dimorphism',
  SEXUAL_DIMORPHISM: 'Sexual dimorphism',
  NO_SEXUAL_DIMORPHISM: 'No sexual dimorphism',
  MELANISTIC: 'Melanistic',
  type: 'display',
  name: 'display'
  },
  behaviour: {
  help: 'This species exhibits which form of behaviour?',
  SEXUAL_CANNIBALISM: 'Sexual cannibalism',
  MONANDROUS: 'Monandrous',
  VOCALISATION: 'Vocalisation',
  CRYPSIS: 'Crypsis',
  HOARDING: 'Hoarding',
  HIBERNATION: 'Hibernation',
  GAME_PLAYING: 'Game playing',
  PLAYFUL: 'Playful',
  TERRITORIAL: 'Territorial',
  NON_TERRITORIAL: 'Non territorial',
  BIPARENTAL_CARE: 'Biparental care',
  COOPERATIVE_BREEDING: 'Cooperative breeding',
  TOOL_MAKING: 'Tool making',
  PROBLEM_SOLVING: 'Problem solving',
  DIVISION_OF_LABOUR: 'Division of labour',
  SUPERORGANISM: 'Superorganism',
  ANAUTOGENY: 'Anautogeny',
  MASS_PROVISIONING: 'Mass provisioning',
  PRECOCIAL: 'Precocial',
  ALTRICIAL: 'Altricial',
  AUTOTOMIC: 'Autotomic',
  ECTOTHERMIC: 'Ectothermic',
  ADHESION: 'Adhesion',
  POLYPHYODONT: 'Polyphyodont',
  VIVIPAROUS: 'Viviparous',
  REGURGITATION: 'Feeding through regurgitation',
  MULTIVOLTINE: 'Multivoltine',
  BIVOLTINE: 'Bivoltine',
  UNIVOLTINE: 'Univoltine',
  SEMIVOLTINE: 'Semivoltine',
  METAMORPHOSIS: 'Metamorphosis',
  RUTTING: 'Rutting',
  WHELPING: 'Whelping',
  FARROWING: 'Farrowing',
  SWIMMING: 'Swimming',
  DECUMBENT: 'Decumbent',
  ETHYLENE_RIPENING: 'Ethylene ripening',
  MIGRATORY: 'Migratory',
  type: 'behaviour',
  name: 'behaviour'
  },
  sense: {
  help: 'Which sense does this species favour?',
  SIGHT: 'Sight',
  MOVEMENT: 'Movement',
  SMELL: 'Smell',
  SPATIAL: 'Spatial',
  MEMORY: 'Memory',
  ECHOLOCATION: 'Echolocation',
  type: 'sense',
  name: 'sense'
  },
  crypsis: {
  CAMOUFLAGE: 'Camouflage',
  NOCTURNALITY: 'Nocturnality',
  SUBTERRANEAN: 'Subterranean',
  MIMICRY: 'Mimicry',
  VISUAL: 'Visual',
  OLFACTORY: 'Olfactory',
  AUDITORY: 'Auditory',
  },
  allochory: {
  ANEMOCHORY: 'Anemochory',
  HYDROCHORY: 'Hydrochory',
  ZOOCHORY: 'Zoochory',
  ANTHROPOCHORY: 'Anthropochory',
  type: 'allochory',
  name: 'allochory'
  },
  reproductiveContainer: {
  CONE: 'Cone',
  type: 'reproductiveContainer',
  name: 'reproductive container'
  },
  communication: {
  VOCALISATION: 'Vocalisation',
  POSTURING: 'Posturing',
  type: 'communication',
  name: 'communication'
  },
  matingSystem: {
  POLYGYNOUS: 'Polygynous',
  MONOGAMOUS: 'Monogamous',
  type: 'matingSystem',
  name: 'mating system'
  },
  physiology: {
  NEGATIVE_ALLELOPATHY: 'Negative allelopathy',
  POSITIVE_ALLELOPATHY: 'Positive allelopathy',
  C3_CARBON_FIXATION: 'C3 carbon fixation',
  NITROGEN_FIXING: 'Nitrogen fixing',
  MYCORRHIZAL: 'Mycorrhizal',
  ECTOMYCORRHIZAL: 'Ectomycorrhizal',
  DORMANCY: 'Dormancy',
  EVERGREEN: 'Evergreen',
  DECIDUOUS: 'Deciduous',
  CONIFEROUS: 'Coniferous',
  ADVENTITIOUS:'Adventitious',
  NYCTINASTY:'Nyctinasty',
  XEROMORPHIC: 'Xeromorphic',
  SUCCULENT: 'Succulent',
  DROUGHT_TOLERANT: 'Drought tolerant',
  FIRE_TOLERANT: 'Fire tolerant',
  FIRE_RESISTANT: 'Fire resistant',
  POLLUTION_TOLERANT: 'Pollution tolerant',
  PH_TOLERANT: 'pH tolerant',
  SALT_TOLERANT: 'Salt tolerant',
  FROST_TOLERANT: 'Frost tolerant',
  HEAT_TOLERANT: 'Heat tolerant',
  NITROGEN_TOLERANT: 'Nitrogen tolerant',
  HEAVY_METAL_TOLERANT: 'heavy metal tolerant',
  ACID_RAIN_TOLERANT: 'Acid rain tolerant',
  COMPACT_SOIL_TOLERANT: 'Compact soil tolerant',
  FLORAL_SCENT: 'Floral scent',
  AROMATIC: 'Aromatic',
  MONOCARPIC: 'Monocarpic',
  POLYCARPIC: 'Polycarpic',
  PYROPHYTIC: 'Pyrophytic',
  SEROTINOUS: 'Serotinous',
  STYPTIC: 'Styptic',
  BIOLUMINESCENCE: 'Bioluminescence',
  type: 'physiology',
  name: 'physiology'
  },
  collective: {
  help: 'What is the term for a collective of this species?',
  SOUNDER: 'Sounder',
  SLOTH: 'Sloth',
  MURMURATION: 'Murmuration',
  PACK: 'Pack',
  type: 'collective',
  name: 'collective'
  },
  ecology: {
  DIGGING: 'Digging',
  SCRAPING: 'Scraping',
  ROOTING: 'Rooting',
  SCAVENGING: 'Scavenging',
  type: 'ecology',
  name: 'ecology'
  },
  characteristic: {
  help: 'Which characteristic/s does this species display?',
  PERENNIAL: 'Perennial',
  ANNUAL: 'Annual',
  BIENNIAL: 'Biennial',
  HERBACEOUS: 'Herbaceous',
  DIOECIOUS: 'Dioecious',
  MONOECIOUS: 'Monoecious',
  SYNOECIOUS: 'Synoecious',
  PERFECT: 'Perfect',
  COMPLETE: 'Complete',
  DICOTYLEDON: 'Dicot',
  MONOCOTYLEDON: 'Monocot',
  CAULIFLORY: 'Cauliflory',
  RAMIFLORY: 'Ramiflory',
  PUBESCENT: 'Pubescent',
  CHAMAEPHYTE: 'Chamaephyte',
  FIBROUS_ROOT_SYSTEM: 'Fibrous root system',
  TAPROOT_SYSTEM: 'Taproot system',
  KIN_SELECTION: 'Kin selection',  
  BROADLEAF: 'Broadleaf',
  AERIAL_ROOTS: 'Aerial roots',
  EPICORMIC_ROOTS: 'Epicormic shoots',
  BASAL_ROOTS: 'Basal shoots',
  RUNNER: 'Runner',
  CLIMBER: 'Climber',
  BUTTRESS_ROOT: 'Buttress root',
  MONOPODIAL: 'Monopodial',
  APICAL_DOMINANCE: 'Apical dominance',
  POLYMORPHIC: 'Polymorphic',
  CRYPTIC_SPECIES_COMPLEX: 'Cryptic species complex',  
  RHIZOMORPHS: 'Rhizomorphs',
  GEOPHYTE: 'Geophyte',
  RICTAL_BRISTLES: 'Rictal bristles',
  DEHISCENCE: 'Dehiscence',
  EXPLOSIVE_DEHISCENCE: 'Explosive dehiscence',
  RESIN_CANAL: 'Resin canal',
  APOSEMATIC: 'Aposematic'
  },
  climate: {
  HOT: 'Hot',
  DRY: 'Dry',
  TEMPERATE: 'Temperate',
  COOL: 'Cool',
  TROPICAL: 'Tropical',
  CONTINENTAL: 'Continental',
  DROUGHT_TOLERANT: 'Drought-tolerant',
  type: 'climate',
  name: 'climate'
  },
  pollination: {
  ALLOGAMY: 'Allogamy',
  ANEMOPHILY: 'Anemophily',
  HYDROPHILY: 'Hydrophily',
  ENTOMOPHILY: 'Entomophily',
  AMBOPHILY: 'Ambophily',
  MELITTOPHILY: 'Melittophily',
  PSYCHOPHILY: 'Psychophily',
  PHALAENOPHILY: 'Phalaenophily',
  SONICATION: 'Sonication',
  GENERALISED_SYNDROME: 'Generalised syndrome',
  CLEISTOGAMY: 'Cleistogamy'
  },
  stipeCharacter: {
  RING: 'Ring',
  RING_AND_VOLVA: 'ring and volva',
  BARE: 'Bare',
  NA: 'N/A',
  SHORT: 'short',
  STUMPY: 'stumpy',
  CLUB_LIKE: 'Club-like',
  WARTS: 'warts',
  HOLLOW: 'hollow',
  PRUINOSE: 'pruinose',
  PARTIAL_VEIL: 'Partial veil',
  type: 'stipeCharacter',
  name: 'stipe character'
  },
  stemCharacter: {
    HOLLOW: 'hollow',
    TERETE: 'terete',
    HAIRY: 'Hairy',
    GLAUCOUS: 'Glaucous',
    FARINOSE: 'Farinose',
    SCURFY: 'Scurfy',
    VISCOUS: 'Viscous',
    PUNCTATE: 'Punctate',
    PAPILLATE: 'Papillate',
    TUBERCULATE: 'Tuberculate',
    RUGOSE: 'Rugose',
    GLABROUS: 'Glabrous',
    PUBESCENT: 'Pubescent',
  },
  gillAttachment: {
    ADNATE: 'Adnate',
    ADNEXED: 'Adnexed',
    DECURRENT: 'Decurrent',
    EMARGINATE: 'Emarginate',
    FREE: 'Free',
    Seceding: 'Seceding',
    SINUATE: 'Sinuate',
    SUBDECURRENT: 'Subdecurrent',
    NA: 'N/A',
    type: 'gillAttachment',
    name: 'gill attachment'
  },
  grouping: {
    LARGE_GROUPS: 'large groups',
    CLUSTERS: 'clusters',
    LARGE_CLUSTERS: 'large clusters',
    SCATTERED_CLUSTERS: 'scattered clusters',
    FAIRY_RINGS: 'fairy rings',
    GREGARIOUS: 'gregarious',
    NUMEROUS: 'numerous',
    type: 'grouping',
    name: 'grouping'
  },
  propagation: {
    RHIZOMES: 'Rhizomes',
    SEEDS: 'Seeds',
    SUCKERS: 'Suckers',
    STOLONS: 'Stolons',
    BULBS: 'Bulbs',
    TUBERS: 'Tubers',
    CORMS: 'Corms',
    PLANTLETS: 'Plantlets',
    KEIKIS: 'Keikis',
    APOMIXIS: 'Apomixis',
    type: 'propagation',
    name: 'propagation'
  },
  seedDispersal: {
    AUTOCHORY: 'autochory',
    ANEMOCHORY: 'anemochory',
    HYDROCHORY: 'Hydrochory',
    ZOOCHORY: 'Zoochory',
    ANTHROPOCHORY: 'Anthropochory',
  },
  exposure: {
    FULL_SUN: 'Full sun',
    PARTIAL_SUN: 'Partial Sun',
    PARTIAL_SHADE: 'Partial Shade',
    SHADE: 'shade'
  },
  nutType: {
    ACORN: 'acorn',
    HAZELNUT: 'hazelnut',
    CHESTNUT: 'chestnut',
  },
  surface: {
    GLAUCOUS: 'Glaucous',
    FARINOSE: 'Farinose',
    SCURFY: 'Scurfy',
    VISCOUS: 'Viscous',
    PUNCTATE: 'Punctate',
    PAPILLATE: 'Papillate',
    TUBERCULATE: 'Tuberculate',
    RUGOSE: 'Rugose',
    GLABROUS: 'Glabrous',
    PUBESCENT: 'Pubescent',
    TOMENTOSE: 'tomentose',
  },
  texture: {
    LEATHERY: 'Leathery',
    FLESHY: 'Fleshy',
    GLOSSY: 'Glossy',
    WOOLY: 'Wooly',
    TOMENTOSE: 'tomentose',
    SCALY: 'Scaly',
    ROUGH: 'Rough',
    SMOOTH: 'Smooth',
    VELVETY: 'Velvety',
    HAIRY: 'Hairy',
  },
  treeShape: {
    help: "Which descrption is the best match for this tree?",
    COLUMNAR: 'Columnar',
    OPEN_HEAD_IRREGULAR: 'Open head irregular',
    WEEPING: 'Weeping',
    PYRAMIDAL: 'Pyramidal',
    GLOBE: 'Globe',
    FASTIGIATE: 'Fastigiate',
    VASE: 'Vase',
    HORIZONTAL_SPREADING: 'Horizontal spreading',
    NARROW_DOMED: 'Narrow domed'
  },
  crownShape: {
    OVOID_CONIC: 'Ovoid-conic',
    CONIC: 'Conic',
    DOMED: 'Domed',
    SPIRE_LIKE: 'Spire-like',
    SLENDER: 'Slender'
  },
  barkType: {
    SMOOTH: 'Smooth',
    LENTICELS: 'Lenticels',
    PEELING_STRIPS: 'Peeling strips',
    VERTICAL_CRACK: 'Vertical cracks',
    VERTICAL_STRIPS: 'Vertical strips',
    SCALES: 'Scales',
    PLATES: 'Plates',
    INTERSECTING_RIDGES: 'Intersecting ridges',
    UNINTERRUPTED_RIDGES: 'Uninterrupted ridges',
    RIDGES_BROKEN_HORIZONTALLY: 'Ridges broken horizontally',
    PAPER_LIKE: 'Paper-like',
    SQUARE_CRACKED: 'Square-cracked',
    RESINOUS: 'Resinous',
    THICK: 'Thick'
  },
  coneShape: {
    BARREL_SHAPED: 'Barrel-shaped',
    GLOBULAR: 'Globular'
  },
  leafVenation: {
    ARCUATE: 'Arcuate',
    DICHOTOMOUS: 'Dichotomous',
    LONGITUDINAL: 'Longitudinal',
    PARALLEL: 'Parallel',
    PINNATE: 'Pinnate',
    RETICULATE: 'Reticulate',
    ROTATE: 'Rotate',
    TRANSVERSE: 'Transverse',
  },
  flowerShape: {
    TRUMPET_SHAPED: 'Trumpet-shaped',
    BILABIATE: 'Bilabiate',
    REGULAR: 'Regular',
    ACTINOMORPHIC: 'Actinomorphic',
    ZYGOMORPHIC: 'Zygomorphic'
  },
  branchArrangement: {
    HORIZONTAL: 'Horizontal',
    WHORLS: 'Whorls'
  },
  leafFeatures: {
    BLUNT_TIPS: 'Blunt tips',
    STOMATAL_LINES: 'Stomatal lines',
    DROOPING: 'Drooping'
  },
  leafFolding: {
    CARINATE: 'Carinate',
    CONDUPLICATE: 'Conduplicate',
    CUCULLATE: 'Cucullate',
    INVOLUTE: 'Involute',
    PLICATE: 'Plicate',
    REDUPLICATE: 'Reduplicate',
    REVOLUTE: 'Revolute',
    SUPERVOLUTE: 'Supervolute',
  },
  mushroomGroup: {    
    MYCOTROPHS: 'Mycotrophs',
    POLYPORES: 'Polypores',
    BOLETES: 'Boletes',
    PUFFBALLS: 'Puffballs',
    GILLED_MUSHROOMS: 'Gilled Mushrooms',
    CHANTERELLES_AND_TRUMPETS: 'Chanterelles and Trumpets',
    TOOTHED_MUSHROOMS: 'Toothed Mushrooms',
    STINKHORNS: 'Stinkhorns',
    CUP_FUNGI: 'Cup Fungi',
    BIRDS_NEST_FUNGI:'Bird\'s Nest Fungi',
    TRUE_MORELS_AND_VERPAS: 'True Morels and Verpas',
    FALSE_MORELS: 'False Morels',
    SADDLES: 'Saddles',
    JELLY_FUNGI: 'Jelly Fungi',
    CLUBS_AND_CORALS: 'Clubs and Corals',
    CRUST_FUNGI: 'Crust Fungi'
  },
  units: [
    { lifeSpan: [ 'DD', 'MM', 'YY'] },
    { gestation: [ 'DD', 'MM', 'YY'] },
    { weaning: [ 'DD', 'MM', 'YY'] },
    { germination: [ 'DD', 'WW', 'MM', 'YY'] },
    { height: [ 'm', 'cm', 'mm'] },
    { diameter: [ 'm', 'cm', 'mm'] },
    { circumference: [ 'm', 'cm', 'mm'] },
    { trunkDiameter: [ 'm', 'cm', 'mm'] },
    { capDiameter: [ 'm', 'cm', 'mm'] },
    { umbelDiameter: [ 'cm', 'mm'] },
    { capWidth: [ 'm', 'cm', 'mm'] },
    { infructescenceWidth: [ 'm', 'cm', 'mm'] },
    { width: [ 'm', 'cm', 'mm'] },
    { breadth: [ 'm', 'cm', 'mm'] },
    { capHeight: [ 'm', 'cm', 'mm'] },
    { shelfWidth: [ 'm', 'cm', 'mm'] },
    { shelfThickness: [ 'm', 'cm', 'mm'] },
    { length: [ 'm', 'cm', 'mm'] },
    { leafLength: [ 'm', 'cm', 'mm'] },
    { infructescenceLength: [ 'm', 'cm', 'mm'] },
    { juvenileLeafLength: [ 'm', 'cm', 'mm'] },
    { leafWidth: [ 'm', 'cm', 'mm'] },
    { petalLength: [ 'cm', 'mm'] },
    { petalWidth: [ 'cm', 'mm'] },
    { petioleLength: [ 'cm', 'mm'] },
    { bractLength: [ 'cm', 'mm'] },
    { fruitWidth: [ 'cm', 'mm'] },
    { fruitLength: [ 'cm', 'mm'] },
    { fruitDiameter: [ 'cm', 'mm'] },
    { fruitHeight: [ 'cm', 'mm'] },
    { flowerDiameter: [ 'cm', 'mm'] },
    { flowerLength: [ 'cm', 'mm'] },
    { coneDiameter: [ 'cm', 'mm'] },
    { coneLength: [ 'cm', 'mm'] },
    { maleConeLength: [ 'cm', 'mm'] },
    { femaleConeLength: [ 'cm', 'mm'] },
    { coneWidth: [ 'cm', 'mm'] },
    { maleConeWidth: [ 'cm', 'mm'] },
    { femaleConeWidth: [ 'cm', 'mm'] },
    { stalkHeight: [ 'm', 'cm', 'mm'] },
    { stemHeight: [ 'm', 'cm', 'mm'] },
    { stemDiameter: [ 'm', 'cm', 'mm'] },
    { stipeLength: [ 'm', 'cm', 'mm'] },
    { tailLength: [ 'm', 'cm', 'mm'] },
    { leafletLength: [ 'cm', 'mm'] },
    { leafletWidth: [ 'cm', 'mm'] },
    { queenLength: [ 'cm', 'mm'] },
    { queenWingspan: [ 'cm', 'mm'] },
    { workerLength: [ 'cm', 'mm'] },
    { workerWingspan: [ 'cm', 'mm'] },
    { maleLength: [ 'cm', 'mm'] },
    { maleWingspan: [ 'cm', 'mm'] },
    { stipeWidth: [ 'm', 'cm', 'mm'] },
    { wingSpan: [ 'm', 'cm', 'mm'] },
    { tongueLength: [ 'cm', 'mm'] },
    { phValue: ['pH']},
    { weight: [ 'g', 'kg']},
    { queenWeight: [ 'g']},
    { workerWeight: [ 'g']},
    { maleWeight: [ 'g']},
  ],
};

//Kuo, M. (2007, January). Key to major groups of mushrooms. Retrieved from the MushroomExpert.Com Web site: http://www.mushroomexpert.com/major_groups.html