import * as SD from 'api/snapdragon/trait-types';

export const fungiTraits = [
    { name: 'Agaricus bisporus', traits: [
        { name: 'cap shape', value: 'convex', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "brown", language: 'en' },
        { name: 'stipe character', value : "ring", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
    ]},
    { name: 'Amanita virosa', traits: [
        { name: 'cap shape', value: 'convex', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value : SD.howEdible.DEADLY, language: 'en', description: 'highly poisonous even in small quantities; symptoms delayed' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "ring and volva", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
        { name: 'flesh', value : "pure white", language: 'en' },
    ]},
    { name: 'Mycena rosea', traits: [
        { name: 'cap shape', value: 'conical', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value : SD.howEdible.POISONOUS, language: 'en', description: 'contains small amounts of muscarine' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "adnate", language: 'en' },
    ]},
    { name: 'Clitocybe odora', traits: [
        { name: 'cap shape', value: 'flat', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value: SD.howEdible.EDIBLE, language: 'en', description: 'aniseed flavour' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
    ]},
    { name: 'Amanita pantherina', traits: [
        { name: 'cap shape', value: 'flat', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value : SD.howEdible.POISONOUS, language: 'en', description: 'sickness and hallucinations' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "ring and volva", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
    ]},
    { name: 'Boletus edulis', traits: [
        { name: 'cap shape', value: 'convex', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en', description: 'tasty; high in protein, vitamins, minerals and fibre' },
        { name: 'hymenium type', value : "pores", language: 'en' },
        { name: 'spore print colour', value : "brown", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "adnate", language: 'en' },
        { name: 'flesh', value : "white, yellowing", language: 'en' }
    ], context: [
        { name: 'look-alikes', values: [ 'Tylopilus felleus' ]},
        { name: 'trees', values: [ 'Quercus', 'Fagus', 'Pinus'] }
    ]},
    { name: 'Amanita muscaria', traits: [
        { name: 'cap shape', value: 'flat', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value : SD.howEdible.POISONOUS, language: 'en', description: 'deadly in quantity' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "ring and volva", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
    ]},
    { name: 'Laccaria amethystina', traits: [
        { name: 'cap shape', value: 'convex', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value: SD.howEdible.EDIBLE, language: 'en', description: 'not particularly tasty' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
    ]},
    { name: 'Scleroderma citrinum', traits: [
        { name: 'cap shape', value: 'potato shaped', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value : SD.howEdible.POISONOUS, language: 'en', description: 'significant stomach upsets' },
        { name: 'hymenium type', value : "gleba", language: 'en' },
        { name: 'spore print colour', value : "brown, purple-black", language: 'en' },
        { name: 'stipe character', value : "NA", language: 'en' },
        { name: 'gill attachment', value : "NA", language: 'en' },
        { name: 'flesh', value : "off-white, purple, black", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Lycoperdon perlatum' ]},
    ]},
    { name: 'Auricularia auricula-judae', traits: [
        { name: 'cap shape', value: 'NA', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.EDIBLE, language: 'en', description: 'common in Chinese hot and sour soup' },
        { name: 'hymenium type', value : "smooth", language: 'en' },
        { name: 'spore print colour', value : "white, cream", language: 'en' },
        { name: 'stipe character', value : "none or very short", language: 'en' },
        { name: 'gill attachment', value : "NA", language: 'en' },
    ]},
    { name: 'Coprinus comatus', traits: [
        { name: 'cap shape', value: 'conical', language: 'en' },
        { name: 'cap colour', value: 'white, white scales', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en', description: 'mild flavour' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "black", language: 'en' },
        { name: 'stipe character', value : "ring", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
        { name: 'flesh', value : "white", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Coprinus picaceus' ]},        
    ]},
    { name: 'Coprinus picaceus', traits: [
        { name: 'cap shape', value: 'conical', language: 'en' },
        { name: 'cap colour', value: 'black, white scales', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.POISONOUS, language: 'en', description: 'mild flavour' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "black", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
        { name: 'flesh', value : "white", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Coprinus comatus' ]},        
    ]},
    { name: 'Grifola frondosa', traits: [
        { name: 'cap shape', value: 'no, offset', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.PARASITIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "pores", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "NA", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
    ]},
    { name: 'Amanita phalloides', traits: [
        { name: 'cap shape', value: 'flat, convex', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value: SD.howEdible.DEADLY, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "ring and volva", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
    ]},
    { name: 'Lycoperdon pyriforme', traits: [
        { name: 'cap shape', value: 'spherical, pear shaped', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gleba", language: 'en' },
        { name: 'spore print colour', value : "white, browning", language: 'en' },
        { name: 'stipe character', value : "short, stumpy", language: 'en' },
        { name: 'gill attachment', value : "NA", language: 'en' },
        { name: 'grouping', value : "gregarious, numerous", language: 'en' },        
        { name: 'smell', value : "unpleasant, gas-like", language: 'en' },        
    ], context: [
        { name: 'look-alikes', values: [ 'Scleroderma citrinum', 'Amanita muscaria']},
    ]},
    { name: 'Lycoperdon perlatum', traits: [
        { name: 'cap shape', value: 'spherical, pear shaped', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.EDIBLE, language: 'en' },
        { name: 'hymenium type', value : "gleba", language: 'en' },
        { name: 'spore print colour', value : "olive, brown", language: 'en' },
        { name: 'stipe character', value : "club-like, with warts", language: 'en' },
        { name: 'gill attachment', value : "NA", language: 'en' },
        { name: 'flesh', value : "white, browning", language: 'en' },
        { name: 'grouping', value : "usually gregarious", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Scleroderma citrinum', 'Amanita muscaria' ]},
    ]},
    { name: 'Pleurotus ostreatus', traits: [
        { name: 'cap shape', value: 'offset', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white, lilac", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
        { name: 'flesh', value : "white, tough in stem", language: 'en' },
        { name: 'smell', value : "mushroomy", language: 'en' },
        { name: 'grouping', value : "large clusters", language: 'en' },
    ]},
    { name: 'Hericium erinaceus', traits: [
        { name: 'cap shape', value: 'NA', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.PARASITIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "teeth", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "NA", language: 'en' },
        { name: 'gill attachment', value : "NA", language: 'en' },
    ]},
    { name: 'Laetiporus sulphureus', traits: [
        { name: 'cap shape', value: 'flat', language: 'en' },
        { name: 'ecological type', value: `${SD.ecoType.SAPROTROPHIC}, ${SD.ecoType.PARASITIC}`, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "pores", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "NA", language: 'en' },
        { name: 'gill attachment', value : "no", language: 'en' },
        { name: 'flesh', value : "yellow, orange, white", language: 'en' },
        { name: 'grouping', value : "large groups", language: 'en' },
    ]},
    { name: 'Craterellus cornucopioides', traits: [
        { name: 'cap shape', value: 'infundibuliform', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "ridges", language: 'en' },
        { name: 'spore print colour', value : "buff, cream", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
    ]},
    { name: 'Gyromitra esculenta', traits: [
        { name: 'cap shape', value: 'convex, brain-like', language: 'en' },
        { name: 'ecological type', value: `${SD.ecoType.MYCORRHIZAL}, ${SD.ecoType.PARASITIC}`, language: 'en' },
        { name: 'how edible', value: SD.howEdible.DEADLY, language: 'en' },
        { name: 'hymenium type', value : "smooth", language: 'en' },
        { name: 'spore print colour', value : "buff, yellow", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "NA", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Morchella esculenta' ]},
    ]},
    { name: 'Omphalotus olearius', traits: [
        { name: 'cap shape', value: 'infundibuliform', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value : SD.howEdible.POISONOUS, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "yellow", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
        { name: 'grouping', value : "clusters", language: 'en' },
    ]},
    { name: 'Amanita rubescens', traits: [
        { name: 'cap shape', value: 'infundibuliform', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value : SD.howEdible.POISONOUS, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "yellow", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Macrolepiota procera' ]},     
    ]},
    { name: 'Cantharellus cibarius', traits: [
        { name: 'cap shape', value: 'infundibuliform', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "ridges", language: 'en' },
        { name: 'spore print colour', value : "yellow, cream", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
        { name: 'flesh', value : "white", language: 'en' },
        { name: 'smell', value : "fruity", language: 'en' },
        { name: 'vitamins', value : "C, D", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Omphalotus olearius', 'Omphalotus illudens', 'Omphalotus olivascens', 'Hygrophoropsis aurantiaca' ]},
        { name: 'trees', values: [ 'Quercus', 'Fagus', 'Betula'] }
    ]},
    { name: 'Hygrophoropsis aurantiaca', traits: [
        { name: 'cap shape', value: 'depressed, infundibuliform', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.INEDIBLE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white, cream", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
        { name: 'flesh', value : "as cap", language: 'en' }
    ], context: [
        { name: 'look-alikes', values: [ 'Cantharellus cibarius' ]},
        { name: 'trees', values: [ 'Quercus', 'Fagus', 'Betula'] }
    ]},
    { name: 'Agaricus xanthodermus', traits: [
        { name: 'cap shape', value: 'convex', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value : SD.howEdible.POISONOUS, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "brown", language: 'en' },
        { name: 'stipe character', value : "ring", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
        { name: 'flesh', value : "white, bruising yellow", language: 'en' },
        { name: 'smell', value : "iodine, ink", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Agaricus campestris' ]}
    ]},
    { name: 'Clitocybe rivulosa', traits: [
        { name: 'cap shape', value: 'depressed', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.DEADLY, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
    ]},
    { name: 'Agaricus campestris', traits: [
        { name: 'cap shape', value: 'flat, convex', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "chocolate brown", language: 'en' },
        { name: 'stipe character', value : "ring", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
        { name: 'flesh', value : "white, bruising pink", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Agaricus xanthodermus' ]}
    ]},
    { name: 'Marasmius oreades', traits: [
        { name: 'cap shape', value: 'convex, umbonate', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "adnate", language: 'en' },
    ]},
    { name: 'Morchella esculenta', traits: [
        { name: 'cap shape', value: 'conical, ovate, honeycomb', language: 'en' },
        { name: 'ecological type', value: `${SD.ecoType.SAPROTROPHIC}, ${SD.ecoType.MYCORRHIZAL}`, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "smooth", language: 'en' },
        { name: 'spore print colour', value : "yellow", language: 'en' },
        { name: 'stipe character', value : "bare, hollow", language: 'en' },
        { name: 'gill attachment', value : "no", language: 'en' },
        { name: 'flesh', value : "thin, white", language: 'en' },
        { name: 'grouping', value : "scattered clusters", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Gyromitra esculenta' ]},
    ]},
    { name: 'Tylopilus felleus', traits: [
        { name: 'cap shape', value: 'convex', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value : "inedible", language: 'en' },
        { name: 'hymenium type', value : "pores", language: 'en' },
        { name: 'spore print colour', value : "pink, buff", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "adnate", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Boletus edulus' ]},
        { name: 'trees', values: [ 'Quercus', 'Fagus', 'Pinus'] }
    ]},
    { name: 'Lactarius sanguifluus', traits: [
        { name: 'cap shape', value: 'depressed', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "tan", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
    ]},
    { name: 'Macrolepiota procera', traits: [
        { name: 'cap shape', value: 'umbonate', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "ring", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
    ], context: [
        { name: 'look-alikes', values: [ 'Amanita rubescens', 'Amanitas', 'Posinous Lepiotas' ]},
    ]},
    { name: 'Amanita caesarea', traits: [
        { name: 'cap shape', value: 'convex', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "ring and volva", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
    ]},
    { name: 'Lactarius deliciosus', traits: [
        { name: 'cap shape', value: 'depressed', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.MYCORRHIZAL, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "tan", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
    ]},
    { name: 'Fistulina hepatica', traits: [
        { name: 'cap shape', value: 'flat', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.PARASITIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.EDIBLE, language: 'en' },
        { name: 'hymenium type', value : "pores", language: 'en' },
        { name: 'spore print colour', value : "pink", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "decurrent", language: 'en' },
    ]},
    { name: 'Chlorophyllum rhacodes', traits: [
        { name: 'cap shape', value: 'convex, umbonate', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.CHOICE, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "white", language: 'en' },
        { name: 'stipe character', value : "ring", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
    ]},
    { name: 'Coprinopsis picacea', traits: [
        { name: 'cap shape', value: 'conical', language: 'en' },
        { name: 'ecological type', value: SD.ecoType.SAPROTROPHIC, language: 'en' },
        { name: 'how edible', value: SD.howEdible.POISONOUS, language: 'en' },
        { name: 'hymenium type', value : "gills", language: 'en' },
        { name: 'spore print colour', value : "black", language: 'en' },
        { name: 'stipe character', value : "bare", language: 'en' },
        { name: 'gill attachment', value : "free", language: 'en' },
    ]},
];