import * as traitEnums from 'api/traits/trait-types';

export const fungiDescriptions = [
    {
        ids: ['Cantharellus cibarius', 'Omphalotus olearius', 'Hygrophoropsis aurantiaca'],
        type: 'lookalike',
        description: 'The false chanterelle (Hygrophoropsis aurantiaca) has a similar appearance and can be confused with the chanterelle. Distinguishing factors are color (the true chanterelle is uniform egg-yellow, while the false chanterelle is more orange in hue and graded, with darker center) and attachment of gills to the stem (the true chanterelle has ridges or wrinkles, which can be quite deep, but not true gills).'
    },
    {
        ids: ['Morchella esculenta', 'Gyromitra esculenta'],
        type: 'lookalike',
        description: 'The false morel (Gyromitra esculenta) has a wrinkled or cerebral appearance, the ridges and pit of the true morel ressemble honeycomb. The cap of the false morel is reddish-brown, purplish-brown or dark brown. Only the true morel has a hollow stem.'
    },
    {
        ids: ['Laetiporus sulphureus', 'Laetiporus cincinnatus'],
        type: 'lookalike',
        description: 'The pore surface of L. sulphureus is bright yellow and cream/white for L. cincinnatus. L. cincinnatus grows away from the tree in a rosette of individual caps. L. sulphureus grows in shelves at the base of the tree. Both favour oaks. '
    },
    // {
    //     ids: ['Laetiporus sulphureus', 'Polyporus squamosus'],
    //     type: 'lookalike',
    //     description: 'Something or other. '
    // },
];

export const getFungiTraits = (enums) => {
    const SD = enums || traitEnums;
    return [
    { name: 'Agaricus bisporus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONVEX },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "brown" },
        { name: SD.name.STIPE_CHARACTER, value : "ring" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ ''] }
    ]},
    { name: 'Amanita virosa', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.CONVEX}, ${SD.capShape.FLAT}` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value : SD.howEdible.DEADLY, description: 'highly poisonous even in small quantities; symptoms delayed' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "ring and volva" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
        { name: SD.name.FLESH, value : "pure white" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.MIXED_WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.DECIDUOUS, SD.treeType.CONIFERS ] },
    ]},
    { name: 'Mycena rosea', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONICAL },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value : SD.howEdible.POISONOUS, description: 'contains small amounts of muscarine' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "adnate" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.DECIDUOUS ] },
    ]},
    { name: 'Clitocybe odora', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.FLAT },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.EDIBLE, description: 'aniseed flavour' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.DECIDUOUS ] },
    ]},
    { name: 'Amanita pantherina', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.FLAT },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value : SD.howEdible.POISONOUS, description: 'sickness and hallucinations' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "ring and volva" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.BEECH ] },
    ]},
    { name: 'Boletus edulis', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONVEX },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE, description: 'tasty; high in protein, vitamins, minerals and fibre' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.PORES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "brown" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "adnate" },
        { name: SD.name.FLESH, value : "white, yellowing" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Tylopilus felleus' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND ]},
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.OAK, SD.treeType.BEECH, SD.treeType.PINE, SD.treeType.CHESTNUT, SD.treeType.CORK] }
    ]},
    { name: 'Amanita muscaria', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.FLAT}, ${SD.capShape.CONVEX}` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value : SD.howEdible.POISONOUS, description: 'deadly in quantity' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "ring and volva" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.MIXED_WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.BEECH, SD.treeType.PINE, SD.treeType.BIRCH, SD.treeType.DECIDUOUS, SD.treeType.CONIFERS ] },
    ]},
    { name: 'Laccaria amethystina', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONVEX },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.EDIBLE, description: 'not particularly tasty' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.ELDER, SD.treeType.DECIDUOUS ] },
    ]},
    { name: 'Scleroderma citrinum', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.POTATO_SHAPED },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value : SD.howEdible.POISONOUS, description: 'significant stomach upsets' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GLEBA },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "brown, purple-black" },
        { name: SD.name.STIPE_CHARACTER, value : "NA" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" },
        { name: SD.name.FLESH, value : "off-white, purple, black" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Lycoperdon perlatum' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.COMMONS, SD.habitat.PASTURE, SD.habitat.HEATH, SD.treeType.MIXED_WOODLAND] },
        { name: SD.name.SYMBIONTS, values: [ ] },
    ]},
    { name: 'Auricularia auricula-judae', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.NA },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.EDIBLE, description: 'common in Chinese hot and sour soup' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.SMOOTH },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white, cream" },
        { name: SD.name.STIPE_CHARACTER, value : "none or very short" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND, SD.habitat.DEAD_WOOD ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.ELDER, SD.treeType.SYCAMORE, SD.treeType.BEECH, SD.treeType.ASH, SD.treeType.DECIDUOUS ] },
    ]},
    { name: 'Coprinus comatus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONICAL },
        { name: SD.name.CAP_COLOUR, value: 'white, white scales' },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE, description: 'mild flavour' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "black" },
        { name: SD.name.STIPE_CHARACTER, value : "ring" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
        { name: SD.name.FLESH, value : "white" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Coprinopsis picacea' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WASTELAND, SD.habitat.LAWNS ] },
        { name: SD.name.SYMBIONTS, values: [] },  
    ]},
    { name: 'Coprinopsis picacea', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONICAL },
        { name: SD.name.CAP_COLOUR, value: 'black, white scales' },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.POISONOUS, description: 'mild flavour' },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "black" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
        { name: SD.name.FLESH, value : "white" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Coprinus comatus' ]},       
        { name: SD.name.ECOLOGY, values: [] },
        { name: SD.name.SYMBIONTS, values: [] },   
    ]},
    { name: 'Grifola frondosa', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.OFFSET },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.PARASITIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.PORES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "NA" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Meripilus giganteus' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.OAK, SD.treeType.DECIDUOUS] },  
    ]},
    { name: 'Amanita phalloides', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.FLAT}, ${SD.capShape.CONVEX}` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.DEADLY },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "ring and volva" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Amanita caesarea', 'Tricholoma equestre', 'Amanita muscaria' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.OAK, SD.treeType.PINE, SD.treeType.CHESTNUT] },  
    ]},
    { name: 'Lycoperdon pyriforme', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.SPHERICAL}, ${SD.capShape.PEAR_SHAPED}` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GLEBA },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white, browning" },
        { name: SD.name.STIPE_CHARACTER, value : "short, stumpy" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" },
        { name: SD.name.GROUPING, value : "gregarious, numerous" },  
        { name: SD.name.SMELL, value : "unpleasant, gas-like" },        
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Scleroderma citrinum', 'Amanita muscaria']},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.DEAD_WOOD ] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.DECIDUOUS, SD.treeType.CONIFERS] },  
    ]},
    { name: 'Lycoperdon perlatum', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.SPHERICAL}, ${SD.capShape.PEAR_SHAPED}` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.EDIBLE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GLEBA },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "olive, brown" },
        { name: SD.name.STIPE_CHARACTER, value : "club-like, with warts" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" },
        { name: SD.name.FLESH, value : "white, browning" },
        { name: SD.name.GROUPING, value : "usually gregarious" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Scleroderma citrinum', 'Amanita muscaria' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND, SD.treeType.DECIDUOUS, SD.habitat.WOODLAND_LITTER, SD.habitat.PASTURE, SD.habitat.GRASSLAND ] },
        { name: SD.name.SYMBIONTS, values: [] },  
    ]},
    { name: 'Pleurotus ostreatus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.OFFSET },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white, lilac" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
        { name: SD.name.FLESH, value : "white, tough in stem" },
        { name: SD.name.SMELL, value : "mushroomy" },
        { name: SD.name.GROUPING, value : "large clusters" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND] },
        { name: SD.name.SYMBIONTS, values: [SD.habitat.DEAD_WOOD, SD.treeType.BEECH, SD.treeType.DECIDUOUS] },  
    ]},
    { name: 'Hericium erinaceus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.NA },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.PARASITIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.TEETH },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "NA" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" },
        { name: SD.name.FLESH, value : "white" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: ['Hericium cirrhatum' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.HARDWOODS, SD.habitat.TRUNKS, SD.habitat.DEAD_WOOD] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.BEECH, SD.treeType.TURKEY_OAK] },  
    ]},
    { name: 'Laetiporus sulphureus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.FLAT },
        { name: SD.name.CAP_COLOUR, value: 'sulpur yellow, fading' },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.SAPROTROPHIC}, ${SD.ecoType.PARASITIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.PORES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "NA" },
        { name: SD.name.GILL_ATTACHMENT, value : "no" },
        { name: SD.name.FLESH, value : "yellow, orange, white" },
        { name: SD.name.GROUPING, value : "large groups" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: ['Polyporus squamosus', 'Meripilus giganteus', 'Laetiporus huroniensis', 'Laetiporus gilbertsonii', 'Laetiporus cincinnatus' ]},
        { name: SD.name.ECOLOGY, values: [SD.habitat.DEAD_WOOD, SD.treeType.HARDWOODS, SD.habitat.TRUNKS, SD.habitat.STUMPS ] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.BEECH, SD.treeType.OAK, SD.treeType.PRUNUS, SD.treeType.SALIX, SD.treeType.ROBINIA, SD.treeType.EUCALYPTUS, SD.treeType.CERATONIA, SD.treeType.YEW] },  
    ]},
    { name: 'Craterellus cornucopioides', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.INFUNDIBULIFORM },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.RIDGES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "buff, cream" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WOODLAND_LITTER, SD.treeType.BEECH, SD.treeType.OAK, SD.treeType.BROAD_LEAF ] },
        { name: SD.name.SYMBIONTS, values: [ ] },
    ]},
    { name: 'Gyromitra esculenta', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.CONVEX}, ${SD.capShape.BRAIN_LIKE}` },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.MYCORRHIZAL}, ${SD.ecoType.PARASITIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.DEADLY },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.SMOOTH },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "buff, yellow" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Morchella esculenta' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WASTELAND ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.ELM, SD.treeType.ASH, SD.treeType.PINE, SD.treeType.BEECH, SD.treeType.SYCAMORE ] },
    ]},
    { name: 'Omphalotus olearius', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.INFUNDIBULIFORM },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value : SD.howEdible.POISONOUS },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "yellow" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
        { name: SD.name.GROUPING, value : "clusters" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Cantharellus cibarius', 'Hygrophoropsis aurantiaca' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.ROOTS, SD.habitat.DEAD_WOOD ] },
    ]},
    { name: 'Amanita rubescens', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.INFUNDIBULIFORM },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value : SD.howEdible.POISONOUS },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "yellow" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Macrolepiota procera' ]},     
        { name: SD.name.ECOLOGY, values: [ SD.treeType.DECIDUOUS ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.CONIFERS ] }
    ]},
    { name: 'Cantharellus cibarius', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.INFUNDIBULIFORM },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.RIDGES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "yellow, cream" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
        { name: SD.name.FLESH, value : "white" },
        { name: SD.name.SMELL, value : "fruity" },
        { name: SD.name.VITAMINS, value : "C, D" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Omphalotus olearius', 'Omphalotus illudens', 'Hygrophoropsis aurantiaca' ] },
        { name: SD.name.ECOLOGY, values: [ SD.habitat.MOSS ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.OAK, SD.treeType.BEECH, SD.treeType.BIRCH ] }
    ]},
    { name: 'Hygrophoropsis aurantiaca', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.INFUNDIBULIFORM}, ${SD.capShape.INFUNDIBULIFORM}` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.INEDIBLE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white, cream" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
        { name: SD.name.FLESH, value : "as cap" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Cantharellus cibarius' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.OAK, SD.treeType.BEECH, SD.treeType.BIRCH] }
    ]},
    { name: 'Agaricus xanthodermus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONVEX },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value : SD.howEdible.POISONOUS },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "brown" },
        { name: SD.name.STIPE_CHARACTER, value : "ring" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
        { name: SD.name.FLESH, value : "white, bruising yellow" },
        { name: SD.name.SMELL, value : "iodine, ink" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Agaricus campestris' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND, SD.habitat.GRASSLAND, SD.habitat.HEDGEROWS ] }
    ]},
    { name: 'Clitocybe rivulosa', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.DEPRESSED },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.DEADLY },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Marasmius oreades' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.LAWNS, SD.habitat.MEADOW ] },
        { name: SD.name.SYMBIONTS, values: [ ] }
    ]},
    { name: 'Agaricus campestris', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.FLAT}, ${SD.capShape.CONVEX}` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "chocolate brown" },
        { name: SD.name.STIPE_CHARACTER, value : "ring" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
        { name: SD.name.FLESH, value : "white, bruising pink" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Agaricus xanthodermus' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.PASTURE, SD.habitat.MEADOW, SD.habitat.WASTELAND, SD.habitat.FIELDS ] }
    ]},
    { name: 'Marasmius oreades', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.CONVEX}, ${SD.capShape.UMBONATE}` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "adnate" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Clitocybe rivulosa' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.LAWNS, SD.habitat.MEADOW, SD.habitat.FIELDS, SD.habitat.DUNES ] },
        { name: SD.name.SYMBIONTS, values: [ ] }
    ]},
    { name: 'Morchella esculenta', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.CONICAL}, ${SD.capShape.OVATE}, ${SD.capShape.HONEYCOMB}` },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.SAPROTROPHIC}, ${SD.ecoType.MYCORRHIZAL}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.SMOOTH },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "yellow" },
        { name: SD.name.STIPE_CHARACTER, value : "bare, hollow" },
        { name: SD.name.GILL_ATTACHMENT, value : "no" },
        { name: SD.name.FLESH, value : "thin, white" },
        { name: SD.name.GROUPING, value : "scattered clusters" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Gyromitra esculenta' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.ORCHARDS, SD.habitat.WOODLAND, SD.habitat.WASTELAND ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.ELM, SD.treeType.ASH, SD.treeType.PINE, SD.treeType.BEECH, SD.treeType.SYCAMORE ] }
    ]},
    { name: 'Tylopilus felleus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONVEX },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value : SD.howEdible.INEDIBLE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.PORES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "pink, buff" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "adnate" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Boletus edulis' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND ]},
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.OAK, SD.treeType.BEECH] }
    ]},
    { name: 'Lactarius sanguifluus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.DEPRESSED },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "tan" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.CONIFERS, SD.habitat.DUNES ]},
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.PINE, 'Pseudotsuga menziesii', 'Onychium contiguum'] }
    ]},
    { name: 'Macrolepiota procera', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.UMBONATE },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "ring" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Amanita rubescens', 'Amanitas', 'Posinous Lepiotas' ]},
    ]},
    { name: 'Amanita caesarea', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONVEX },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "ring and volva" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Amanita phalloides', 'Amanita muscaria' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.OAK, SD.treeType.CONIFERS, SD.treeType.PINE, SD.treeType.CHESTNUT] },  
    ]},
    { name: 'Lactarius deliciosus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.DEPRESSED },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "tan" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.PINE, SD.treeType.CONIFERS] },  
    ]},
    { name: 'Fistulina hepatica', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.FLAT },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.PARASITIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.PORES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "pink" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ '' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.DEAD_WOOD, SD.habitat.WOOD ] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.OAK, SD.treeType.SWEET_CHESTNUT, SD.treeType.EUCALYPTUS, SD.treeType.POPLAR, SD.treeType.BIRCH] },  
    ]},
    { name: 'Chlorophyllum rhacodes', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.CONVEX}, ${SD.capShape.UMBONATE}`  },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "ring" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
    ]},
    { name: 'Amanita ponderosa', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.HEMI_SPHERICAL}, ${SD.capShape.CONVEX}, ${SD.capShape.FLAT}` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "pink" },
        { name: SD.name.STIPE_CHARACTER, value : "ring and volva" },
        { name: SD.name.GILL_ATTACHMENT, value : "free" },
        { name: SD.name.SMELL, value : "earthy" },
        { name: SD.name.FLESH, value : "white" },
        { name: 'contact air', value : "pinkish" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Amanita phalloides' , 'Amanita curtipes', 'Amanita verna' ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.OAK, SD.treeType.CORK, SD.treeType.PINE, SD.treeType.EUCALYPTUS] },  
    ]},
    { name: 'Tricholoma equestre', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.FLAT}` },
        { name: SD.name.CAP_COLOUR, value: `yellow, yellow-green, brown` },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.POISONOUS },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.STIPE_COLOUR, value : "yellow" },
        { name: SD.name.GILL_ATTACHMENT, value : "adnexed" },
        { name: SD.name.GILL_COLOUR, value : "yellow" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WOODLAND ] },
        { name: SD.name.SYMBIONTS, values: [] },  
    ]},
    { name: 'Boletus pinophilus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONVEX },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.EDIBLE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.PORES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "olive-brown" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "adnexed" },
        { name: SD.name.FLESH, value : "white, no change on bruising" },
        { name: SD.name.SMELL, value : "pleasant, pork crackling" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Boletus edulis', 'Tylopilus felleus' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND ]},
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.PINE, SD.treeType.FIR, SD.treeType.SPRUCE] }
    ]},
    { name: 'Hydnum repandum', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.DEPRESSED },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.TEETH },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
        { name: SD.name.FLESH, value : "white, orange on bruising" },
        { name: SD.name.SMELL, value : "pleasant" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Hydnum umbilicatum', 'Hydnum albidum', 'Hydnum albomagnum', 'Hydnum rufescens' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.MIXED_WOODLAND, SD.habitat.MOSS, SD.habitat.RINGS, SD.habitat.SOIL ]},
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.CONIFERS, SD.treeType.DECIDUOUS] }
    ]},
    { name: 'Laetiporus cincinnatus', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.FLAT },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.SAPROTROPHIC}, ${SD.ecoType.PARASITIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.PORES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "NA" },
        { name: SD.name.GILL_ATTACHMENT, value : "no" },
        { name: SD.name.FLESH, value : "yellow, orange, white" },
        { name: SD.name.GROUPING, value : "large groups" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Laetiporus sulphureus', 'Polyporus squamosus' ]},
        { name: SD.name.ECOLOGY, values: [SD.habitat.DEAD_WOOD, SD.treeType.HARDWOODS, ] },
        { name: SD.name.SYMBIONTS, values: [SD.treeType.BEECH, SD.treeType.OAK, SD.treeType.PRUNUS, SD.treeType.SALIX, SD.treeType.ROBINIA, SD.treeType.EUCALYPTUS, SD.treeType.CERATONIA] },  
    ]},
    { name: 'Craterellus tubaeformis', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.INFUNDIBULIFORM },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.MYCORRHIZAL}, ${SD.ecoType.SAPROTROPHIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.RIDGES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "salmon" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
        { name: SD.name.GROUPING, value : "large groups" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Laetiporus sulphureus', 'Polyporus squamosus' ]},
        { name: SD.name.ECOLOGY, values: [SD.habitat.CONIFERS, SD.habitat.MOSS, SD.habitat.DEAD_WOOD ] },
        { name: SD.name.SYMBIONTS, values: ['Pseudotsuga menziesii', 'Tsuga heterophylla'] },  
    ]},
    { name: 'Hydnum umbilicatum', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.DEPRESSED },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.TEETH },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Hydnum repandum' ]},
        { name: SD.name.ECOLOGY, values: [SD.habitat.CONIFERS, SD.habitat.DAMP ] },
        { name: SD.name.SYMBIONTS, values: [''] },  
    ]},
    { name: 'Hericium americanum', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.NA },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.TEETH },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Hericium coralloides' ]},
        { name: SD.name.ECOLOGY, values: ['' ] },
        { name: SD.name.SYMBIONTS, values: [''] },  
    ]},
    { name: 'Hericium coralloides', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.NA },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.TEETH },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Hericium americanum' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.HARDWOODS ] },
        { name: SD.name.SYMBIONTS, values: [''] },  
    ]},
    { name: 'Calvatia gigantea', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.NA },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.MYCORRHIZAL },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GLEBA },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "brown" },
        { name: SD.name.STIPE_CHARACTER, value : "NA" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Amanitas, Earthball' ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.DECIDUOUS, SD.habitat.MEADOW, SD.habitat.FIELDS ] },
        { name: SD.name.SYMBIONTS, values: [''] },  
    ]},
    { name: 'Clitocybe nuda', traits: [
        { name: SD.name.CAP_SHAPE, value: 'convex, umbonate' },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.SAPROTROPHIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "pink" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "emarginate" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ SD.habitat.WOODLAND_LITTER ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.DECIDUOUS, SD.habitat.MEADOW, SD.habitat.FIELDS ] },
        { name: SD.name.SYMBIONTS, values: ['Picea abies', 'Pinus sylvestris'] },  
    ]},
    { name: 'Armillaria mellea', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.CONVEX },
        { name: SD.name.ECO_TYPE, value: SD.ecoType.PARASITIC },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.EDIBLE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "ring" },
        { name: SD.name.GILL_ATTACHMENT, value : "subdecurrent, adnate" }
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.HARDWOODS, SD.habitat.DEAD_WOOD ] },
        { name: SD.name.SYMBIONTS, values: [ 'Entoloma abortivum', 'Pseudotsuga menziesii', 'Tsuga heterophylla'] },
    ]},
    { name: 'Armillaria tabescens', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.CONVEX}, ${SD.capShape.FLAT}` },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.PARASITIC}, ${SD.ecoType.SAPROTROPHIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.EDIBLE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
        { name: SD.name.GROUPING, value : "clusters" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.HARDWOODS, SD.habitat.DEAD_WOOD ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.OAK] },
    ]},
    { name: 'Entoloma abortivum', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.CONVEX}, ${SD.capShape.FLAT}` },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.PARASITIC}, ${SD.ecoType.SAPROTROPHIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.EDIBLE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "pink" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
        { name: SD.name.GROUPING, value : "clusters" },
        { name: SD.name.FLESH, value : "white" },
        { name: SD.name.SMELL, value : "strongly mealy" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.HARDWOODS, SD.habitat.WOODLAND_LITTER, SD.habitat.DEAD_WOOD ] },
        { name: SD.name.SYMBIONTS, values: [ 'Armillaria mellea'] },
    ]},
    { name: 'Polyporus squamosus', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.DEPRESSED}, ${SD.capShape.OFFSET}` },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.PARASITIC}, ${SD.ecoType.SAPROTROPHIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.EDIBLE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.PORES },
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "decurrent" },
        { name: SD.name.GROUPING, value : "clusters" },
        { name: SD.name.FLESH, value : "white" },
        { name: SD.name.SMELL, value : "watermelon rind" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ 'Laetiporus sulphureus']},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.HARDWOODS, SD.habitat.DEAD_WOOD ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.ELM, SD.treeType.MAPLE, SD.treeType.ASH, SD.treeType.PLANE, SD.treeType.WILLOW ] },
    ]},
    { name: 'Sarcoscypha coccinea', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.NA },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.SAPROTROPHIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE},
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.SMOOTH },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" },
        // { name: SD.name.SPORE_PRINT_COLOUR, value : "pink" },
    ], context: [
        // { name: SD.name.LOOK_ALIKES, values: [ 'Laetiporus sulphureus']},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.WOODLAND_LITTER, SD.habitat.DAMP, SD.habitat.DEAD_WOOD ] },
        { name: SD.name.SYMBIONTS, values: [ ] },
    ]},
    { name: 'Sparassis crispa', traits: [
        { name: SD.name.CAP_SHAPE, value: SD.capShape.NA },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.SAPROTROPHIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE},
        { name: SD.name.SPORE_PRINT_COLOUR, value : "white to cream" },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.SMOOTH },
        { name: SD.name.STIPE_CHARACTER, value : "bare or missing" },
        { name: SD.name.GILL_ATTACHMENT, value : "NA" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ ]},
        { name: SD.name.ECOLOGY, values: [ SD.treeType.CONIFERS, SD.habitat.TREE_BASE ] },
        { name: SD.name.SYMBIONTS, values: [ SD.treeType.LARCH, SD.treeType.SPRUCE, SD.treeType.PINE, SD.treeType.CEDAR] },
    ]},
    { name: 'Lepista personata', traits: [
        { name: SD.name.CAP_SHAPE, value: `${SD.capShape.CONVEX}, ${SD.capShape.FLAT}` },
        { name: SD.name.ECO_TYPE, value: `${SD.ecoType.SAPROTROPHIC}` },
        { name: SD.name.HOW_EDIBLE, value: SD.howEdible.CHOICE},
        { name: SD.name.SPORE_PRINT_COLOUR, value : "pink" },
        { name: SD.name.HYMENIUM_TYPE, value : SD.hymeniumType.GILLS },
        { name: SD.name.GILL_COLOUR, value : "pink, cream to light brown" },
        { name: SD.name.STIPE_CHARACTER, value : "bare" },
        { name: SD.name.GILL_ATTACHMENT, value : "emarginate" },
        { name: SD.name.GROUPING, value : "fairy rings" },
    ], context: [
        { name: SD.name.LOOK_ALIKES, values: [ ]},
        { name: SD.name.ECOLOGY, values: [ SD.habitat.FOREST_EDGE, SD.habitat.PASTURE, SD.habitat.GRASSLAND, SD.habitat.PARKS ] },
        { name: SD.name.SYMBIONTS, values: [] },
    ]},
    { name: 'Xanthoria parietina', traits: [
        { name: SD.name.SUBSTRATE, value: `${SD.substrate.BARK}, ${SD.substrate.WOOD}, ${SD.substrate.ROCK}` },
        { name: SD.name.HABITAT, value: `${SD.treeType.POPLAR}, ${SD.treeType.HARDWOODS}` },
        { name: SD.name.THALLUS_TYPE, value: `${SD.thallusType.FOLIOSE}` },
        { name: SD.name.RHIZINE_TYPE, value: `${SD.rhizineType.SPARSE}, ${SD.rhizineType.HAPTER}` },
        { name: SD.name.ASSOCIATE, value: `${SD.associate.ALGA}`, photobiont: 'Trebouxia' },
        { name: SD.name.POLLUTION_TOLERANCE, value: `${SD.level.HIGH}`},
        { name: SD.name.HEAVY_METAL_TOLERANCE, value: `${SD.level.MEDIUM}`},
        { name: SD.name.MEDICINAL_PROPERTIES, value: `${SD.medicinalProperties.ANTIVIRAL}`},
        { name: SD.name.DISC_WIDTH, value: `<8cm`},
        { name: SD.name.COLOUR, value: `${SD.colour.DARK_YELLOW} - ${SD.colour.ORANGE_RED}`},
        { name: SD.name.LOBE_DIAMETER, value: `1-4mm`},
    ]},
    { name: 'Ramalina fastigiata', traits: [
        { name: SD.name.POLLUTION_TOLERANCE, value: `${SD.level.HIGH}`}
    ]},
    { name: 'Ramalina farinacea', traits: [
        { name: SD.name.HABITAT, value: `${SD.habitat.BARK}, ${SD.habitat.WOOD}, ${SD.habitat.ROCK}` },
        { name: SD.name.THALLUS_TYPE, value: `${SD.thallusType.FRUTICOSE}, ${SD.thallusType.EPIPHYTE}` },
        { name: SD.name.ASSOCIATE, value: `${SD.associate.ALGA}`, photobiont: 'Trebouxia' },
        { name: SD.name.POLLUTION_TOLERANCE, value: `${SD.level.HIGH}`},
        { name: SD.name.COLOUR, value: `${SD.colour.GREEN} - ${SD.colour.GREY}`},
        { name: SD.name.DISC_WIDTH, value: `3-8cm`},
        { name: SD.name.LOBE_LENGTH, value: `1-5cm`},
    ]},
    { name: 'Evernia prunastri', traits: [
        { name: SD.name.SUBSTRATE, value: `${SD.substrate.BARK}, ${SD.substrate.WOOD}` },
        { name: SD.name.HABITAT, value: [ SD.treeType.OAK, SD.treeType.DECIDUOUS, SD.treeType.FIR, SD.treeType.PINE, SD.habitat.FENCES ] },
        { name: SD.name.THALLUS_TYPE, value: `${SD.thallusType.FOLIOSE}` },
        { name: SD.name.ASSOCIATE, value: `${SD.associate.ALGA}`, photobiont: '' },
        { name: SD.name.POLLUTION_TOLERANCE, value: `${SD.level.MEDIUM}`},
        { name: SD.name.DISC_WIDTH, value: `3-4cm`},
        { name: SD.name.COLOUR, value: `${SD.colour.YELLOW} - ${SD.colour.OLIVE_GREEN}`},
        { name: SD.name.USAGE, value: `${SD.usage.PERFUMERY}`},
    ]},
    { name: 'Graphis scripta', traits: [
        { name: SD.name.SUBSTRATE, value: `${SD.substrate.BARK}` },
        { name: SD.name.HABITAT, value: `${SD.treeType.DECIDUOUS}` },
        { name: SD.name.THALLUS_TYPE, value: `${SD.thallusType.CRUSTOSE}` },
        { name: SD.name.ASSOCIATE, value: `${SD.associate.FUNGUS}`, photobiont: 'Stigmidium microspilum.' },
        { name: SD.name.POLLUTION_TOLERANCE, value: `${SD.level.HIGH}`},
        { name: SD.name.COLOUR, value: `${SD.colour.WHITE_GREEN} - ${SD.colour.GREY_GREEN}`},
    ]},
    { name: 'Lobaria pulmonaria', traits: [
        { name: SD.name.SUBSTRATE, value: `${SD.substrate.BARK}` },
        { name: SD.name.HABITAT, value: [ SD.treeType.OAK, SD.treeType.BEECH, SD.treeType.MAPLE, SD.habitat.ROCK ] },
        { name: SD.name.THALLUS_TYPE, value: `${SD.thallusType.FOLIOSE}, ${SD.thallusType.EPIPHYTE}` },
        { name: SD.name.ASSOCIATE, value: `${SD.associate.ALGA}, ${SD.associate.CYNOBACTERIUM}`, photobiont: 'Dictyochloropsis reticulata' },        
        { name: SD.name.POLLUTION_TOLERANCE, value: `${SD.level.LOW}`},
        { name: SD.name.ACID_RAIN, value: `${SD.level.LOW}`},
        { name: SD.name.COLOUR, value: `${SD.colour.BRIGHT_GREEN} - ${SD.colour.PAPER_BROWN}`},
        { name: SD.name.DISC_WIDTH, value: `5-15cm`},
        { name: SD.name.LOBE_WIDTH, value: `1-3cm`},
        { name: SD.name.LOBE_LENGTH, value: `<7cm`},
        { name: SD.name.MEDICINAL_PROPERTIES, value: `${SD.medicinalProperties.ANTISEPTIC}, ${SD.medicinalProperties.ANTI_INFLAMMATORY}`},
        { name: SD.name.USAGE, value: `${SD.usage.PERFUMERY}, ${SD.usage.TANNING}, ${SD.usage.DYING}, ${SD.usage.BREWING}`},
    ]},
    { name: 'Letharia vulpina', traits: [
        { name: SD.name.SUBSTRATE, value: `${SD.substrate.BARK}, ${SD.substrate.EXPOSED_WOOD}` },
        { name: SD.name.HABITAT, value: `${SD.treeType.OAK}, ${SD.treeType.CONIFERS}` },
        { name: SD.name.THALLUS_TYPE, value: `${SD.thallusType.FRUTICOSE}` },
        { name: SD.name.POLLUTION_TOLERANCE, value: `${SD.level.VARIABLE}`},
        { name: SD.name.COLOUR, value: `${SD.colour.BRIGHT_YELLOW_GREEN}`},
        { name: SD.name.DISC_WIDTH, value: `2-7cm`},
        { name: SD.name.MEDICINAL_PROPERTIES, value: `${SD.medicinalProperties.ANTIBACTERIAL}, ${SD.medicinalProperties.ANTICOAGULANT}`},
        { name: SD.name.USAGE, value: `${SD.usage.DYING}, ${SD.usage.POISON}`},
    ]},
    { name: 'Physcia adscendens', traits: [
        { name: SD.name.THALLUS_TYPE, value: `${SD.thallusType.FOLIOSE}` },
        { name: SD.name.DISC_WIDTH, value: `<2cm`},
        { name: SD.name.LOBE_WIDTH, value: `<2mm`},
        { name: SD.name.LOBE_LENGTH, value: `<2mm`},
        { name: SD.name.COLOUR, value: `${SD.colour.GREY}`},
        { name: SD.name.SUBSTRATE, value: `${SD.substrate.TREES}, ${SD.substrate.BRANCHES}` },
        { name: SD.name.HABITAT, value: `${SD.treeType.CONIFERS}` },
        { name: SD.name.BIOINDICATOR, value: SD.element.NITROGEN },
    ]},
    { name: 'Parmelia saxatilis', traits: [
        // { name: SD.name.SUBSTRATE, value: `${SD.substrate.BARK}, ${SD.substrate.EXPOSED_WOOD}` },
        // { name: SD.name.HABITAT, value: [ SD.treeType.OAK, SD.treeType.CONIFERS ] },
        { name: SD.name.THALLUS_TYPE, value: `${SD.thallusType.FOLIOSE}` },
        // { name: SD.name.POLLUTION_TOLERANCE, value: `${SD.level.VARIABLE}`},
        // { name: SD.name.COLOUR, value: `${SD.colour.BRIGHT_YELLOW_GREEN}`},
        // { name: SD.name.DISC_WIDTH, value: `2-7cm`},
        // { name: SD.name.MEDICINAL_PROPERTIES, value: `${SD.medicinalProperties.ANTIBACTERIAL}, ${SD.medicinalProperties.ANTICOAGULANT}`},
        // { name: SD.name.USAGE, value: `${SD.usage.DYING}, ${SD.usage.POISON}`},
    ]},
];};