runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  secure: always
  redirect_http_response_code: 301
  static_files: dist/index.html
  upload: dist/index.html
  http_headers:
    X-Forwarded-Proto: https
- url: /
  static_dir: dist
  secure: always
  redirect_http_response_code: 301
  http_headers:
    X-Forwarded-Proto: https